### ISSUE TITLE
(telegram channel) free HTTP proxy list ,tested and daily updated-کانال تلگرام پروکسی برای واتس اپ.تست شده

### ISSUE THREAD

**Issue by neonramzy** [WhatsApp/proxy#104]
Providing a list of the best free HTTP proxies available on the internet.
Tested before publishing on the Telegram channel.
the health of the servers and their Availability is ensured.
Also, these proxies can be used in many other programs such as telegram and twitter, and various internet browsers.
join here: https://t.me/whatsappproxy98

**Comment by slawlor** [comment]
WhatsApp doesn't support HTTP proxying today, have you tested these with WhatsApps **specifically**? Please close the issue if it doesn't work.

**Comment by alirezabalsa** [comment]
سلام هیچ کدام وصل نمیشه از سیگنالم کمتر این 
واتساپ
