### ISSUE TITLE
error to config HAproxy

### ISSUE THREAD

**Issue by iranazad2023** [WhatsApp/proxy#118]
I got the error at the very last part when I want to manually execute the container as below:

[NOTICE]   (20) : haproxy version is 2.6.7-c55bfdb

[ALERT]    (20) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:57] : fetch method 'ipv4' : failed to parse 'not' as type 'IPv        4 address' at position 1
[ALERT]    (20) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:66] : fetch method 'ipv4' : failed to parse 'not' as type 'IPv        4 address' at position 1
[ALERT]    (20) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:75] : fetch method 'ipv4' : failed to parse 'not' as type 'IPv        4 address' at position 1
[ALERT]    (20) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT]    (20) : config : Fatal errors found in configuration.

Please let me know what I can do to fix that.
Thanks

**Comment by slawlor** [comment]
please see the other issues opened with the same error. You can try and resolve this with removing the #PUBLIC_IP lines from the HAProxy configuration file.
