### ISSUE TITLE
Using domain/sub-domain instead of an IP

### ISSUE THREAD

**Issue by vatanparvar** [WhatsApp/proxy#120]
Hi,

I have hosted Whatsapp proxy server on multiple nodes, and there are subdomains pointing to those nodes.

- proxy1.example.com => Node 1 IP 
- proxy2.example.com => Node 2 IP

Even though https://faq.whatsapp.com/1299035810920553 indicates that domain and subdomains are supported

> ...
> you can set up a proxy using a server with ports 80, 443 or 5222 available and a domain name (or subdomain) that points to the server’s IP address 
> ...

in WhatsApp mobile application, only IP addresses can be entered. When I try to use any domain name, it simply ignores it and doesn't save the setting.

I would appreciate it if you could look into this and let me know what can be done to enable domain name support. 

Cheers.

**Comment by 7gxycn08** [comment]
Not supported on the android app it bugs out.
Maybe it's supported on ios only.

**Comment by delawar77** [comment]
NAME	IP	COUNTRY	RESPONSE TIME
GardenSnakes Proxy #1	141.148.228.97:82	🇳🇱	3ms
GardenSnakes Proxy #2	68.183.8.87:80	🇳🇱	4ms
GardenSnakes Proxy #3	64.227.75.24:82	🇳🇱	9ms
Jaiden051's Proxy	51.14.190.56:5222	🇬🇧	4ms
GardenSnakes Proxy #4	193.123.34.92:443	🇳🇱	3ms
GardenSnakes Proxy #5	158.101.220.0:443	🇳🇱	5ms
Capsload2's USA Proxy	107.191.125.101:443	🇺🇸	3ms
GardenSnakes Proxy #6	34.105.83.231:443	🇺🇸	2ms
Gary-RR's Proxy	141.148.69.176:443	🇺🇸	2ms

**Comment by eozturk1** [comment]
We have added support for hostnames. Closing the task.
