### ISSUE TITLE
config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg

### ISSUE THREAD

**Issue by whherui** [WhatsApp/proxy#122]
I used to README.md to deploy on Oracle Cloud(Operating System: Oracle Linux 7), and got the following error, then I input "ss -tnl", and did't see 80 443 5222 art in the listening status. who can help me? tks

############################################################################################
Certificate generation completed.
/
[NOTICE]   (27) : haproxy version is 2.6.7-c55bfdb
[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:58] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1
[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:67] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1
[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:76] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1
[ALERT]    (27) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT]    (27) : config : Fatal errors found in configuration.
############################################################################################

**Comment by gary-RR** [comment]
Take a look at this:
https://github.com/WhatsApp/proxy/issues/118

**Comment by iranazad2023** [comment]
> I used to README.md to deploy on Oracle Cloud(Operating System: Oracle Linux 7), and got the following error, then I input "ss -tnl", and did't see 80 443 5222 art in the listening status. who can help me? tks
> 
> ############################################################################################ Certificate generation completed. / [NOTICE] (27) : haproxy version is 2.6.7-c55bfdb [ALERT] (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:58] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1 [ALERT] (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:67] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1 [ALERT] (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:76] : fetch method 'ipv4' : failed to parse 'No' as type 'IPv4 address' at position 1 [ALERT] (27) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg [ALERT] (27) : config : Fatal errors found in configuration. ############################################################################################
you have to remove #PUBLIC IP from the proxy_config.cfg. The file is located at .../proxy/src. If you are not familiar with Linux, follow the below command in your terminal. Before you manually execute the container, go to the src directory as follow:

cd proxy
cd src
nano proxy_config.cfg
So the last one would open the file, then you have to erase three #Public IP in your file, then press Esc and save the changes. SO go back to the main directory with the following:
cd ...
cd ...
So now run again:
docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0

good luck!

**Comment by whherui** [comment]
> you have to remove #PUBLIC IP from the proxy_config.cfg. The file is located at .../proxy/src. If you are not familiar with Linux, follow the below command in your terminal. Before you manually execute the container, go to the src directory as follow:
> 
> cd proxy cd src nano proxy_config.cfg So the last one would open the file, then you have to erase three #Public IP in your file, then press Esc and save the changes. SO go back to the main directory with the following: cd ... cd ... So now run again: docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0
> 
> good luck!

tks brother, I solve it
