### ISSUE TITLE
Calling does not work/connect with proxy

### ISSUE THREAD

**Issue by AliZirgach** [WhatsApp/proxy#123]
The proxy was connected and the user (located in a country where WhatsApp is banned) can Text/Voice Msg but when she calls it does not connect through (can't hear her voice properly).

**Comment by gary-RR** [comment]
VOIP (Voice Over IP) is not supported in this release.

**Comment by AliZirgach** [comment]
Thanks, you mean its not supported by this github method of creating an IP that could be used in WhatsApp OR in the proxy feature that WhatsApp recently added to its app?

**Comment by gary-RR** [comment]
VIP simply means making phone calls over the internet. In other words, you won't be able to make phone calls using the WhatsApp proxy in the current version. I believe that feature will be added to future releases of the proxy.

**Comment by AliZirgach** [comment]
Thank you very much
