### ISSUE TITLE
PUBLIC_IP script uses a private IP address

### ISSUE THREAD

**Issue by i-rme** [WhatsApp/proxy#14]
Hi!

Line :27 of set_public_ip_and_start.sh ( proxy/proxy/src/ ) uses 169.254.169.254 to obtain the public IP address of the host, but as that IP is unreachable outside of Meta, it will fail.

I suggest to replace it with a well known service.

**Comment by msalehy** [comment]
Can you share logs? its working for me 
<img width="665" alt="Screenshot 2023-01-05 at 23 21 37" src="https://user-images.githubusercontent.com/14146289/210882648-f9d2a7b4-a1d4-4b55-9612-8e26b2738570.png">

**Comment by slawlor** [comment]
That's actually the IP provided by AWS to resolve your EC2 instance's host. It's provided as a convenience for those running proxies in AWS, it's not required and it is a known + well-documented service. It will try and resolve the public IP of the host using that service, but if it fails it just utilizes the default private ip
