### ISSUE TITLE
Wireshark logs - is content really going via the proxy?

### ISSUE THREAD

**Issue by davidkjackson92** [WhatsApp/proxy#144]
Is there a way to prove that the proxy is working?

I entered a proxy IP and port and the Android app "connected". Seems to work fine.

I can see a few Wireshark connection requests to the proxy IP. But many more requests and responses to 157.240.201.58 which is a Meta IP. This is the same IP I was connected to when I ran WhatsApp without the proxy.

If content is travelling via the proxy, why are there so many IP requests to the "normal" Meta IP and so few requests to the proxy IP?

**Comment by slawlor** [comment]
The proxy IP is for the main chat connection + login. If you're downloading media (pictures, videos, etc) it goes through a CDN which for now is not proxied. Additionally VoIP traffic (video + voice calls) are also not routed through the proxy. If you were to block all Meta-related traffic, say on your router, you'd see that you can still connect + chat which for now is the main goal we are achieving with this proxy.

Media (pic/video/voice msg/etc) will be coming eventually, but it's a larger change in our client applications, so it takes some time.

**Comment by slawlor** [comment]
There's also metrics collection which I believe runs on a different channel than the main chat channel. However you're app is going to be constantly making requests to other endpoints for various things (like media and voip peering). If you want to see if it's really using the proxy for login + chat, then you should really block Meta IPs and you'll see you can still connect (but media + VoIP won't work). I'm not sure what each individual connection is doing to be honest as there's a lot the app is doing in the background
