### ISSUE TITLE
docker-compose Error

### ISSUE THREAD

**Issue by retired-canaria** [WhatsApp/proxy#17]
dock-compose -f /path-to/docker-compose.yml up
ERROR: The Compose file '/path/proxy/proxy/ops/docker-compose.yml' is invalid because:
services.proxy.healthcheck value Additional properties are not allowed ('start_period' was unexpected)

**Comment by msalehy** [comment]
explained in #11 

use below command : 

sudo docker compose -f ops/docker-compose.yml up -d

**Comment by retired-canaria** [comment]
It doesn't help. I'm pointing to the correct path however get the error as below

$ sudo docker-compose -f /etc/whatsapp/proxy/proxy/opsdocker-compose.yml up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.proxy.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
