### ISSUE TITLE
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

### ISSUE THREAD

**Issue by shoshana19** [WhatsApp/proxy#170]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

#### More Details

_Originally posted by @shoshana19 in https://github.com/WhatsApp/proxy/issues/169_

**Comment by Jeancqrk** [comment]
Em qua, 5 de abr de 2023 15:21, Ercan Ozturk ***@***.***>
escreveu:
