### ISSUE TITLE
a few minutes letter 

### ISSUE THREAD

**Issue by kistonw** [WhatsApp/proxy#188]
Thread 2 is about to kill the process.
 >Thread 1 : id=0x7f3f039418a0 act=1 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=5
      1/1    stuck=1 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=4434775682 now=8742562720 diff=4307787038
             curr_task=0x7f3f03648ee0 (tasklet) calls=2200
               fct=0x55c31bcb5ae0(accept_queue_process) ctx=0x55c31be1a400

*>Thread 2 : id=0x7f3f028c5b30 act=1 glob=0 wq=1 rq=0 tl=1 tlsz=1 rqsz=5
      1/2    stuck=1 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=10031268284 now=139390367297 diff=129359099013
             curr_task=0x7f3f03648f30 (tasklet) calls=2202
               fct=0x55c31bcb5ae0(accept_queue_process) ctx=0x55c31be1c440

/usr/local/bin/set_public_ip_and_start.sh: line 83:    36 Aborted                 (core dumped) haproxy -f "$CONFIG_FILE"

**Comment by Everluis58** [comment]
> Thread 2 is about to kill the process.
>  >Thread 1 : id=0x7f3f039418a0 act=1 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=5
>       1/1    stuck=1 prof=0 harmless=0 wantrdv=0
>              cpu_ns: poll=4434775682 now=8742562720 diff=4307787038
>              curr_task=0x7f3f03648ee0 (tasklet) calls=2200
>                fct=0x55c31bcb5ae0(accept_queue_process) ctx=0x55c31be1a400
> 
> *>Thread 2 : id=0x7f3f028c5b30 act=1 glob=0 wq=1 rq=0 tl=1 tlsz=1 rqsz=5
>       1/2    stuck=1 prof=0 harmless=0 wantrdv=0
>              cpu_ns: poll=10031268284 now=139390367297 diff=129359099013
>              curr_task=0x7f3f03648f30 (tasklet) calls=2202
>                fct=0x55c31bcb5ae0(accept_queue_process) ctx=0x55c31be1c440
> 
> /usr/local/bin/set_public_ip_and_start.sh: line 83:    36 Aborted                 (core dumped) haproxy -f "$CONFIG_FILE"
```
``
```
https://odatos.telcel.com/ssh-tunnel

**Comment by kistonw** [comment]
what??

**Comment by kistonw** [comment]
> 

What?

**Comment by eozturk1** [comment]
Will close this issue, please feel free to open it if you are still experiencing it.
