### ISSUE TITLE
The provided document for implementation of the proxy is so vague

### ISSUE THREAD

**Issue by xxamr** [WhatsApp/proxy#19]
the provided manual is so vague and after doing all steps, we could not get connected to our servers.
I think the manual should be more accurate

**Comment by msalehy** [comment]
what is status of your server ? mostly skip to clone this repo, Dockerfile and docker-compose file is in this repo. first step

> 1. Clone the repository to your local machine

**Comment by xxamr** [comment]
I have done all the steps correctly.
Finally I got this message:
    Starting whatsapp_proxy ... done


Showing that the proxy is working properly.


but when I set the IP in proxy filed of the whatsapp I get " can not connect" error

**Comment by slawlor** [comment]
> but when I set the IP in proxy filed of the whatsapp I get " can not connect" error

This unfortunately will be completely dependent on your connectivity and hosting parameters. Can you probe the stats port from your device? That should tell you if you can contact your proxy or not.

**Comment by msalehy** [comment]
Do you have right firewall ? if you are in AWS open below ports : 
Or adjust your provider policy to open below ports . you can reduce base on your need
 80
 443
5222
8080
8443
 8222
8199

**Comment by xxamr** [comment]
I am on Hetzner and firewall is inactive

**Comment by xxamr** [comment]
Is there any need to edit yml files? or set some parameters more than what's provided in the manual?

**Comment by Melbar666** [comment]
Hetzner has a additional firewall for incoming traffic, you can open the ports on the robot config website.
