### ISSUE TITLE
Proxy works fine, but sending pictures is slow

### ISSUE THREAD

**Issue by jayjacklin** [WhatsApp/proxy#193]
Proxy works fine, but sending pictures is slow。

**Comment by slawlor** [comment]
As noted on the github home page, currently media proxying isn't supported (pictures, videos, voice notes, etc).

**Comment by alexdatur** [comment]
can somebody help with media?
Use this config and chats works well on 443, but media dont work on 587 or 7777
docker run -d --name whatsapp-proxy
-p 80:80
-p 8199:8199
-p 587:587
-p 7777:7777
-p 443:443
-e PUBLIC_IP=**...*
--restart always
whatsapp_proxy:1.0
