### ISSUE TITLE
Run on Android?

### ISSUE THREAD

**Issue by abdul-jabbar-ms** [WhatsApp/proxy#208]
Hello, I would like to run it on my Android device. Is it possible to do so?

I have another question. Let's say the client device and a proxy are connected via LAN, but the uplink internet for the proxy is down. Will the messages still be sent to the proxy and wait there until the internet is available? Does it work like that?

**Comment by eozturk1** [comment]
Hi @abdul-jabbar-ms,

The proxies do not keep messages. As for running them on an Android device as a Docker container, [this](https://forums.docker.com/t/installation-running-docker-on-android-devices/130128) tells me that they are not supported.
