### ISSUE TITLE
> NAME	IP	COUNTRY	RESPONSE TIME

### ISSUE THREAD

**Issue by yaghobahmadi** [WhatsApp/proxy#214]
> NAME	IP	COUNTRY	RESPONSE TIME
> GardenSnakes Proxy #1	141.148.228.97:82	🇳🇱	3ms
> GardenSnakes Proxy #2	68.183.8.87:80	🇳🇱	4ms
> GardenSnakes Proxy #3	64.227.75.24:82	🇳🇱	9ms
> Jaiden051's Proxy	51.14.190.56:5222	🇬🇧	4ms
> GardenSnakes Proxy #4	193.123.34.92:443	🇳🇱	3ms
> GardenSnakes Proxy #5	158.101.220.0:443	🇳🇱	5ms
> Capsload2's USA Proxy	107.191.125.101:443	🇺🇸	3ms
> GardenSnakes Proxy #6	34.105.83.231:443	🇺🇸	2ms
> Gary-RR's Proxy	141.148.69.176:443	🇺🇸	2ms

Indian proxy

_Originally posted by @Shovan1233 in https://github.com/WhatsApp/proxy/issues/127#issuecomment-1413482360_

**Comment by eozturk1** [comment]
@yaghobahmadi, are these WhatsApp proxies? What are the ports, TLS use and media configurations?

**Comment by eozturk1** [comment]
I will close this issue until we receive a response.

**Comment by oaksoye09** [comment]
> @yaghobahmadi, are these WhatsApp proxies? What are the ports, TLS use and media configurations?

158.101.220.0:443

**Comment by RADIA57** [comment]
TLS --
