### ISSUE TITLE
Error Code: 50058
Request Id: bec4125b-a529-4dc7-be37-1e1dc5c13a00
Correlation Id: eabec10c-7885-4e5b-91ce-4c66b3830f9d
Timestamp: 2023-09-13T02:10:07.739Z

### ISSUE THREAD

**Issue by Sad1616** [WhatsApp/proxy#223]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

**Comment by Sad1616** [comment]
Error Code: 50058
Request Id: bec4125b-a529-4dc7-be37-1e1dc5c13a00
Correlation Id: eabec10c-7885-4e5b-91ce-4c66b3830f9d
Timestamp: 2023-09-13T02:10:07.739Z

**Comment by eozturk1** [comment]
What is the origin of this error? Can you share more information on your proxy/client?

**Comment by Sad1616** [comment]
Error Code: 50058
Request Id: bec4125b-a529-4dc7-be37-1e1dc5c13a00
Correlation Id: eabec10c-7885-4e5b-91ce-4c66b3830f9d
Timestamp: 2023-09-13T02:10:07.739Z

**Comment by Sad1616** [comment]
Pınar metiner

**Comment by Sad1616** [comment]
> What is the origin of this error? Can you share more information on your proxy/client?
