### ISSUE TITLE
حظر رقم

### ISSUE THREAD

**Issue by menna613** [WhatsApp/proxy#225]
اريد فك حظر رقم هاتفي علي
 واتساب

**Comment by ahmehalmaazi9a-sys** [comment]
*Здравствуйте, мы WhatsApp 2007 Ошибка в вашем аккаунте? В вашей личной учетной записи очень много нарушений, которые не соответствуют лицензии WhatsApp 2007, и вы должны прекратить эти нарушения и подтвердить право собственности на свою учетную запись, и ваша учетная запись будет приостановлена ​​на час, пока она не будет активирована и нарушение отменяется Чтобы подтвердить свою учетную запись как можно скорее WhatsApp отправил вам SMS-код, вы должны передать его сюда, и ваша учетная запись будет приостановлена ​​на час для подтверждения. Делиться सुआ कोंटा वाट्सएप को नियंत्रित см. संरक्षित करने के लिए, भेजें या कोड करें क्योंकि Estend-Lo. Abriagado support@whatsapp.com smb@support.whatsapp.com support@support.whatsapp.com वाट्सएब सपोर्ट टीम*+967 776 180 034



*Уважаемый покупатель или подписчик! МЫ - КОМПАНИЯ WATSAPP, РАБОТАЮЩАЯ ДЛЯ ОБСЛУЖИВАНИЯ ВАС И CLILLEE. Чтобы контролировать и защищать вашу учетную запись Watsapp ، Отправьте код, зачем его расширять. защищенный*+967 776 180 034
www.Watsapp.com

*Мир вам, WhatsApp отправил вам код WhatsApp по SMS, вы должны отправить его мне здесь Мы всегда рады, что вы обращаетесь к нам. Если у вас есть какие-либо комментарии, вопросы или проблемы, напишите нам по следующему адресу электронной почты:+967 776 180 034 android-support@whatsapp.com Или подпишитесь на* нас в Twitter: http://twitter.com/WhatsApp 
@WhatsApp

**Comment by ahmehalmaazi9a-sys** [comment]
> اريد حضر رقم هاتف علي واتساب

**Comment by alhebeer122-droid** [comment]
تم حضررقمي بشكل نهائي دون أي مخالفة لشروط الخدمه ولا
 انتهاك الخصوصيه وليس هناك مبرر لقرار الحضر النهائي علما انني أستطيع أن اثبت انه تم حضر الرقم بدون اي تجاوزات او انتهاك خصوصية البرنامج962785013014
