### ISSUE TITLE
Comprehensive list for ports needed for chat & media WhatsApp proxy

### ISSUE THREAD

**Issue by Terabyte1385** [WhatsApp/proxy#233]
I want to run a WhatsApp proxy. I have set up dynamic DNS & whatever else is necessary.

Now I'm stuck at the ports that need to be opened. Ports 80 and 443 are used by another Docker container.

The part that causes confusion is this command:
`docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 -p 587:587 -p 7777:7777 whatsapp_proxy:1.0`

Does that mean I have to open port 80, 443, 5222, 8080, 8443, 8222, 8199, 587 and 7777?

I need some guidance on:

1. What ports to use or what to change in the commands given that port 80 and 443 are taken;

2. Ports needed to enable media support

Thanks in advance

**Comment by eozturk1** [comment]
1. You can remove the ports 80 and 443 (`-p 80:80 -p 443:443`) and use port 5222 (no TLS). You might also need to remove 80 and 443 binds in the configuration file [here](https://github.com/WhatsApp/proxy/blob/main/proxy/src/proxy_config.cfg).
2. 587 and 7777 are the media ports.

**Comment by fungjigroup** [comment]
Can you share your WhatsApp proxy address for testing?

**Comment by Terabyte1385** [comment]
Sure, it's `wa-proxy.tudorgavriluta.com`.

I was able to connect via port 5222 (@eozturk1 config file change was not needed 😄).

Thank you for the help!

For who stumbles upon the same issue, these are the ports broken down (please note they may be changed if they don't fit your system, this is from my experience - with port 80 and 443 taken by another Docker container) :

| Port | Required? | Usage |
|--------------|-----------------|---------------|
| 5222 | Yes | Chat functionality |
| 587 | No | Media functionality |
| 7777 | No | Media functionality |
