### ISSUE TITLE
WHATSAPP WINDOWS DOESN'T CONNECT WITH CLASH!!!

### ISSUE THREAD

**Issue by Artsruny** [WhatsApp/proxy#234]
Hey guys. I am having a problem connecting to WhatsApp Windows with Clash! Whatsapp web works but WhatsApp Windows does not! Skype and Telegram work normally too. 
I have the latest version of Clash and Windows 11. 
Any solutions?

**Comment by eozturk1** [comment]
Hi @Artsruny,

This repo is specifically for WhatsApp proxy. Please see https://www.whatsapp.com/contact/ for support for support on other issues you may be experiencing.
