### ISSUE TITLE
Can whatsapp’s proxy address use cloudflare’s CDN?

### ISSUE THREAD

**Issue by mrsoshining** [WhatsApp/proxy#245]
Can whatsapp’s proxy address use cloudflare’s CDN?
I set up a proxy server for WhatsApp myself and resolved the domain name to this IP. Can I use CDN?

**Comment by eozturk1** [comment]
If the proxy is running on a server with a publicly accessible IP, the app should be able to connect to it given the phone's network settings are not prohibiting access.

I'll close this issue but if you have follow up questions, feel free to re-open it!
