### ISSUE TITLE
Failed to connect to local system.

### ISSUE THREAD

**Issue by imatthewtanner** [WhatsApp/proxy#246]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

#### Description
Failed to connect to local system.

**Comment by Sujanayasa** [comment]
Okay

Pada Sel, 26 Mar 2024, 11.57, Matthew Tanner ***@***.***>
menulis:

**Comment by eozturk1** [comment]
Hi @imatthewtanner!

Please share more details on the issue you are experiencing in the form.
