### ISSUE TITLE
missing signature key

### ISSUE THREAD

**Issue by spacesoft321** [WhatsApp/proxy#262]
i am try to install it as per youtub videos and other google tips, but not work 

[root@CentOS-79-64-minimal ~]# ls
proxy
[root@CentOS-79-64-minimal ~]# cd proxy
[root@CentOS-79-64-minimal proxy]# docker build proxy/ -t whatsapp_proxy:1.0
Sending build context to Docker daemon 19.46 kB
Step 1/29 : FROM haproxy:lts-alpine
Trying to pull repository docker.io/library/haproxy ...
missing signature key
[root@CentOS-79-64-minimal proxy]#

**Comment by eozturk1** [comment]
Hi @spacesoft321  

This might be due to an old Docker installation. Please update your Docker and try again.

**Comment by eozturk1** [comment]
Closing this task since it's been a while with no replies.
