### ISSUE TITLE
i try it , but when we are install aaPanel its not working , i try many time but same error

### ISSUE THREAD

**Issue by spacesoft321** [WhatsApp/proxy#263]
hello support team 
its good for WhatsApp setting but when we are install aaPanel its not working , i try many time but same error

how set port and ip there , its show 0.0.0.0:443 already use , how we config our server ip and port 

its not working like Squid server ( https://ubuntu.com/server/docs/how-to-install-a-squid-server )

any option to change port and ip address in WhatsApp Proxy GitHub Code

and its not good work in Centos 7

**please update code and commands for Ubuntu dedicated server user with cPanel or aaPanel**

**Comment by eozturk1** [comment]
Hi @spacesoft321!

Sounds like there is another service using that port. You can try and list current active services using `lsof` command. Alternatively, you can update the port in the HaProxy configuration (Search for use of 443) and update your Docker configuration accordingly.

**Comment by spacesoft321** [comment]
**Please update new best Proxy setting for FastWSapi.com  or API4WS.com**


Hi, please update your WhatsApp Business with the following new proxy settings

Porxy Host : 65.109.65.179

Chat Port : 8444
TLS: ON

Media Port : 588

More info you can join this WhatsApp Channel

https://whatsapp.com/channel/0029VaKAOtc9WtCCmRxYEP3t 

![image](https://github.com/WhatsApp/proxy/assets/6949772/d2283cf4-1bc6-42eb-937d-1015f8e5c151)


![image](https://github.com/WhatsApp/proxy/assets/6949772/0227c067-1d66-436e-af2b-5bc2f0bae4af)

**Comment by spacesoft321** [comment]
if any one have issue to setup any Proxy and Docker in aaPanel , Please whatsapp me +91 9 053 054 055

![image](https://github.com/WhatsApp/proxy/assets/6949772/7b026316-01e8-4d50-95c2-58af397498af)
