### ISSUE TITLE
I dont know its working or not on my website FastWSapi.com

### ISSUE THREAD

**Issue by spacesoft321** [WhatsApp/proxy#264]
Hello Sir, 
I want change its default port 443 to 1432

its possible or not , update command for change port in WhatsApp Proxy Setting

[+] Running 1/0
 ✔ Container whatsapp_proxy  Running 

You can testing it on **FastWSapi.com**

2) Open Your WhatsApp

3) Goto:
> ⚙️ Setting

> ��Click Storage and Data

> ��Click Proxy

> ♾️ Setup-Proxy
Insert this proxy address

![image](https://github.com/WhatsApp/proxy/assets/6949772/a86c2149-69c0-4ef9-9f9f-944372f1ab0a)

65.108.81.198
> ✔️ Save

Then back and Check proxy
> Connected
![image](https://github.com/WhatsApp/proxy/assets/6949772/f344a330-fce8-446e-93a4-2b8f7029d7f7)

**Comment by eozturk1** [comment]
You can change the chat port via the "Chat Port" option in the first image you shared. 

Note the proxy also needs to support connections through this port. In the haproxy configuration, you can change the existing 443 port to the port you would like and update the Dockerfile. See example change here: https://github.com/WhatsApp/proxy/commit/fdd36065185e92516402ed8b6cda584e45fc8f7b. You then need to re-run the proxy with the updated configuration.

**Comment by fungjigroup** [comment]
Is your Whatsapp proxy still working? I tried and couldn't connect.

**Comment by spacesoft321** [comment]
yes , my all proxy working 

if you want add proxy setup your vps and dedicated server , i will support 

more info whatsapp me +91 9 053 054 055

![image](https://github.com/WhatsApp/proxy/assets/6949772/8410b85d-4e41-4f98-b959-a0bf331518e7)

**Comment by spacesoft321** [comment]
FastWSapi.com 

api4ws.com

Hi, please update your WhatsApp Business with the following new proxy settings

Porxy Host : 65.109.65.179

Chat Port : 8444
TLS: ON

Media Port : 588

**Comment by fungjigroup** [comment]
Hi, your WhatsApp proxy server does not work

**Comment by fungjigroup** [comment]
Hi, I found that your WhatsApp proxy is not working since today. Please
kindly check, thanks

Albert

**Comment by fungjigroup** [comment]
The WhatsApp proxy is still  not working. Please kindly check!
