### ISSUE TITLE
Whatsapp Setup Workflow (with proxy) does not work in Iran 

### ISSUE THREAD

**Issue by 62w71st** [WhatsApp/proxy#267]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

#### Description
I am given a proxy, but when setting up whatsapp, the QR code fails to load (see the image) presumably because of censorship in Iran. Moreover, the alternative of linking with a cellphone also doesn't succeed. The app errors with "Connect to Wifi", which is basically the app timing out on a URL. 

![whatsapp_qr_capture](https://github.com/WhatsApp/proxy/assets/68923563/9c6d9601-ada6-4f24-bb16-35e2d80985bf)

Tested on Windows Server client with WhatsappDesktop_2.2423.10.0_neutral.....Msixbundle

**Comment by eozturk1** [comment]
Hi! The proxy support is currently only for Android and iOS and we do not support WhatsApp desktop. Please feel free to create a separate issue if you are having trouble with Android or iOS with proxies.
