### ISSUE TITLE
Set HTTP/SOCKS5 proxy on WhatsApp?

### ISSUE THREAD

**Issue by xmha97** [WhatsApp/proxy#27]
Can I set HTTP/SOCKS5 proxy on WhatsApp?

![Screenshot_2023-01-06-09-13-07-321_com whatsapp](https://user-images.githubusercontent.com/23485114/210937969-5e20dc77-8b07-4fe9-8e01-3b2ef593b5c8.jpg)

It doesn't seem to work even locally!

**Comment by slawlor** [comment]
The client doesn't support HTTP or SOCKS proxies. SOCKS "may" come in the future, but it's presently not supported today. You need a straight TCP proxy (which is what we've provided in this repository). Any further client problems, feel free to open a support ticket through WhatsApp, these issues are specific to the proxy itself. Thanks!

**Comment by rlconst** [comment]
Doesn't look like completed
