### ISSUE TITLE
Andriod whatsapp can't send/receive media via proxy,text is ok

### ISSUE THREAD

**Issue by Nicepaul** [WhatsApp/proxy#276]
I have set up a WhatsApp proxy on Ubuntu 20 .WhatsApp proxy works very well on macOS/iOS app, but on Android only can send text, can't send/receive pictures videos and documents. When will it be possible to update the version of WhatsApp to resolve this issue?

**Comment by eozturk1** [comment]
@Nicepaul, can you please submit a bug report about this? Does the proxy you set up support media?

**Comment by Nicepaul** [comment]
ubuntu 20 server
![u2](https://github.com/WhatsApp/proxy/assets/32355166/60193ef7-d260-440d-8dad-679cbe8051e7)

**Comment by Nicepaul** [comment]
I would like to explain my situation. I am in China, and when I use Chinese home broadband or Chinese mobile data to access the internet, my Android phone can send messages through WhatsApp Proxy but cannot send media. However, when I switch to a U.S. SIM card for internet access, WhatsApp Proxy can send both messages and media. In fact, with a U.S. SIM card, there is no need for a proxy at all because the Chinese firewall does not block traffic from U.S. SIM cards.

It appears that Google/Android might be more susceptible to DNS hijacking. On iOS, regardless of the internet connection method, the proxy can send media without any issues. Additionally, I can send media without any trouble on Signal.

I hope WhatsApp can address and resolve this issue.

**Comment by Notower** [comment]
> I have set up a WhatsApp proxy on Ubuntu 20 .WhatsApp proxy works very well on macOS/iOS app, but on Android only can send text, can't send/receive pictures videos and documents. When will it be possible to update the version of WhatsApp to resolve this issue?

**Comment by ahmedxx49xx15594195696** [comment]
![Collage_20240522_074627~3](https://github.com/user-attachments/assets/d8950232-3b9f-461d-98a3-c954eb270870)
