### ISSUE TITLE
WatsaApp

### ISSUE THREAD

**Issue by Aassdd123123** [WhatsApp/proxy#278]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

**Comment by Notower** [comment]
> **Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**
> 
> 
> 
> #### Description
> 
> 
> 
> 
> 
> #### Failed Step
> 
> 
> 
> 
> 
> 
> 
> #### More Details
> 
> 
> 
> 
> 
>
