### ISSUE TITLE
No media is being sent or received on WhatsApp for Android via the proxy

### ISSUE THREAD

**Issue by Nicepaul** [WhatsApp/proxy#281]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

#### Description

I have set up a WhatsApp proxy. While WhatsApp on iOS/macOS can send and receive media, WhatsApp on Android is unable to do so. All ports required by the documentation are open, and there are no error messages during operation. What could be the issue? The proxy IP is 198.23.138.204, and I am located in China. I hope the support team for the proxy can help resolve this issue. Thank you.

#### More Details
Ubuntu20 server

![WX20240720-092709@2x](https://github.com/user-attachments/assets/34073363-6f1b-41f3-8ace-bacbbdcc06fd)
![WX20240720-093833@2x](https://github.com/user-attachments/assets/adc3e2e6-6426-4cff-8c6f-1060ff2e471d)
![signal-2024-07-20-095047_002](https://github.com/user-attachments/assets/c2c5199d-d9ac-476c-9b4d-685c6fa4b66d)

**Comment by Nicepaul** [comment]
![WechatIMG505](https://github.com/user-attachments/assets/95b19c0c-1b40-426f-83d4-188389f58698)

**Comment by Nicepaul** [comment]
Based on the description from https://github.com/WhatsApp/proxy/blob/main/FAQ.md: "You are free to run your own pure TCP proxy as you see fit however, as long as it forwards to g.whatsapp.net. You aren't required to use this realization." I set up port 11143 on 198.23.138.204 to forward to g.whatsapp.net, and text messages are being sent and received normally. However, setting up port 11587 to g.whatsapp.net does not work for media.

**Comment by wenge110110** [comment]
I'm having this problem too.

**Comment by eozturk1** [comment]
@Nicepaul Can you try in the app updating the media port to 587 or 7777 and try that way? Some networks may block traffic in certain ports which might be the issue you are encountering. From your phone network, can you send a CURL request for instance to either of these ports?

Alternatively you can run messaging through port 80 and media through 443 -- which should have a better chance of avoiding any of the port-specific restrictions. You can update the HAproxy config and match your new messaging/media settings on the app.

**Comment by Nicepaul** [comment]
> @Nicepaul Can you try in the app updating the media port to 587 or 7777 and try that way? Some networks may block traffic in certain ports which might be the issue you are encountering. From your phone network, can you send a CURL request for instance to either of these ports?
> 
> Alternatively you can run messaging through port 80 and media through 443 -- which should have a better chance of avoiding any of the port-specific restrictions. You can update the HAproxy config and match your new messaging/media settings on the app.

Thank you for your reply

I tested the network connection to ports 80, 443, 587, and 7777 on 198.23.138.204 using the nc command on both my Android phone and Mac computer. The ports are reachable and not blocked.

The chat port works fine with 443 TLS, 80 non-TLS, or other mapped ports like 11143 (e.g., docker run -it -p 11443:443 -p 111587:587 -p 17777:7777 whatsapp_proxy:1.0). However, the media port does not work with 587, 7777, 1777, 443, or 80. Note that this issue occurs with WhatsApp on Android, while it works fine on iOS. Perhaps the mechanisms between the two are different? Otherwise, why would the same proxy only fail to work for media on WhatsApp for Android?

![WechatIMG511](https://github.com/user-attachments/assets/35781d30-5c20-4d3b-8be6-b26236f48b11)
![WX20@2x](https://github.com/user-attachments/assets/791fb894-9186-4b5e-8e3c-1c4d15b7333f)

**Comment by offer1983** [comment]
Previously identified this issue, some Android phones, especially Huawei, cannot connect to the media server, the connection fails. Recently, media servers on iOS in some regions have also begun to fail to connect. It feels like the GFW has been upgraded.

WhatsApp proxy hasn't been updated for a long time and is outdated.

**Comment by Nicepaul** [comment]
> Previously identified this issue, some Android phones, especially Huawei, cannot connect to the media server, the connection fails. Recently, media servers on iOS in some regions have also begun to fail to connect.
> 
> WhatsApp proxy hasn't been updated for a long time and is outdated. When using curl to connect to port 587, WhatsApp's certificate is displayed, which seems relevant to your issue. According to your description, the session is using a self-signed certificate, while the media part is using WhatsApp's certificate. This situation might result in WhatsApp's certificate being intercepted by the Great Firewall (GFW) of China.
> 
> **1. curel 433：** `curl -k -v https://_._._._:443
> 
> * Trying _._._._:443...
> * Connected to _._._._ (_._._._) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> * CAfile: /etc/ssl/certs/ca-certificates.crt
> * CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> * ALPN, server did not agree to a protocol
> * Server certificate:
> * subject: CN=LNhWYJA0KS6lwr.net
> * start date: Jul 30 09:47:17 2024 GMT
> * expire date: Jul 28 09:47:17 2034 GMT
> * issuer: CN=a5fGg9v04GQb
> * SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> 
> > GET / HTTP/1.1
> > Host: _._._._
> > User-Agent: curl/7.74.0
> > Accept: _/_
> 
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * old SSL session ID is stale, removing
> * TLSv1.3 (IN), TLS alert, close notify (256):
> * Empty reply from server
> * Closing connection 0
> * TLSv1.3 (OUT), TLS alert, close notify (256):
>   curl: (52) Empty reply from server`
> 
> **2. curl 587** `curl -k -v https://_._._._:587
> 
> * Trying _._._._:587...
> * Connected to _._._._ (_._._._) port 587
> * ALPN: curl offers h2,http/1.1
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256 / X25519 / id-ecPublicKey
> * ALPN: server accepted h2
> * Server certificate:
> * subject: C=US; ST=California; L=Menlo Park; O=Meta Platforms, Inc.; CN=*.whatsapp.net
> * start date: May  9 00:00:00 2024 GMT
> * expire date: Aug  7 23:59:59 2024 GMT
> * issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
> * SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> * Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
> * Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
> * using HTTP/2
> * [HTTP/2] [1] OPENED stream for https://_._._._:587/
> * [HTTP/2] [1] [:method: GET]
> * [HTTP/2] [1] [:scheme: https]
> * [HTTP/2] [1] [:authority: _._._._:587]
> * [HTTP/2] [1] [:path: /]
> * [HTTP/2] [1] [user-agent: curl/8.5.0]
> * [HTTP/2] [1] [accept: _/_]
> 
> > GET / HTTP/2
> > Host: _._._._:587
> > User-Agent: curl/8.5.0
> > Accept: _/_
> 
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
>   < HTTP/2 400
>   < content-length: 101
>   < content-type: text/html; charset=utf-8
>   < access-control-allow-origin: *
>   < proxy-status: proxy_internal_response; e_isproxyerr="AcJA-r1rnCm7SkMnPePYz2KKmIR3BhEoMsTbgINh6vFZiPGRVq78V7DLxZGKaA"; e_proxy="AcKg9KKSQs4jm6bG16R4slUaxeqpFivFbgGzYQw8W33BBaGVan9zXLTLWUNl_QJWf3k2NjYKt07GXas"; e_fb_binaryversion="AcKTdf6mSeFbfTksib5aQwMpRQV7K0CSo26qNmYwXlFqsYIJBWZKwGhIntreYb8R6Ua5wBdgRFocbOtrf0lkHXuE4bd4xhWbilA"; e_fb_httpversion="AcJg8IzZE0UEUmBOfjiRJoOGhJ7W-w5C-v4fgBr-iLjYStnbXESMArE2_8vm"; e_fb_hostheader="AcLBlA_I4Y8ZpoEl72aKaY6zTgsztJVeSmP04dwYYbxQcjwcWiFDiPJ6xhV3Ff9M2lh6tVPfRxwLS2U"; e_fb_requesttime="AcLX7KTZKl_PmMY7t5M3UG94Gxv11Ry_VGM3grrDhk8dgFS3RDvAJv4exzvuFNVNzVHkVtxtDw"; e_fb_responsebytes="AcL54pjS4M4nhaAeqARLCHkkBRp32vQeCc5ILxVPQ5Dv9JMxWWK-TjlfYqiA"; e_fb_requestsequencenumber="AcI5SocCP1gcX8QsAW5KfK22tF5JV1eqv-Lh2RzsiD8lty_W7Tiyc2Anfw"; e_fb_proxycode="AcKgF_ixA4QFKshh_VkrKAuKNAP_GShA2ATuHcPzdRRZ1MSPKnKfdKKXlSYU"; e_fb_builduser="AcIjmcGYd2Mdl8ac88iIoBI0uDpu7oe1ugZ650OOTKBbOKwgzbcvez1aKHcuALnf6QY"; e_fb_vipport="AcLXkDGYZFVPdRzQpXFYsRdcJLc9gy_AytEk1GtmEGg8RhJol2mKwiMYIUdB"; e_clientaddr="AcKo22cRTBL12qwmHTFEJ_n0fkrPFmWPTLrXd1lZqEStk6nbFcI0qqGuL5lEDNZdD8XLTK6nvsNbMEU5UQ"; e_fb_vipaddr="AcKfaUqqt1k2xd-gpgloOOFD4clIVKnHusXTDPbRblER-iPk-2EuYtWlJFOc-7OXjCh3K0Tx"; e_fb_configversion="AcKVVxEcA89yxsb18dTfbiKfMviz7fmlIQDZCpf2kMid4zbqmQb-GeWbSvBZrg"
>   < date: Tue, 30 Jul 2024 10:12:51 GMT
>   <
> 
> <title>WhatsApp Error</title>
> # WhatsApp Error
> `

Thank you for your response. You are right, data packets containing the 'WhatsApp' field will be blocked by the Chinese firewall. This issue needs to be resolved by an official update to the Docker code.

![WX20240730-190713@2x](https://github.com/user-attachments/assets/e86c0e49-cca9-4f71-9489-2fb70e099c4a)
![WX20240730-190815@2x](https://github.com/user-attachments/assets/dcf511a7-c357-4269-8c2f-6f635bc8268a)

**Comment by Nicepaul** [comment]
> @Nicepaul Can you try in the app updating the media port to 587 or 7777 and try that way? Some networks may block traffic in certain ports which might be the issue you are encountering. From your phone network, can you send a CURL request for instance to either of these ports?
> 
> Alternatively you can run messaging through port 80 and media through 443 -- which should have a better chance of avoiding any of the port-specific restrictions. You can update the HAproxy config and match your new messaging/media settings on the app.

I have provided curl request information as instructed. I'm eager to know if there are any upcoming updates or improvements to the WhatsApp proxy program.

**Comment by Nicepaul** [comment]
As the Chinese firewall is constantly improving, this proxy code has not kept up, resulting in 'Media Unavailable'. We would appreciate it if the program code could be updated regularly.

**Comment by bilogic** [comment]
> Previously identified this issue, some Android phones, especially Huawei, cannot connect to the media server, the connection fails. Recently, media servers on iOS in some regions have also begun to fail to connect.
> 
> WhatsApp proxy hasn't been updated for a long time and is outdated. When using curl to connect to port 587, WhatsApp's certificate is displayed, which seems relevant to your issue. According to your description, the session is using a self-signed certificate, while the media part is using WhatsApp's certificate. This situation might result in WhatsApp's certificate being intercepted by the Great Firewall (GFW) of China.

Thanks for sharing, do you know a work around?

**Comment by alexdatur** [comment]
can somebody help with media?
Use this config and chats works well on 443, but media dont work on 587 or 7777
docker run -d --name whatsapp-proxy
-p 80:80
-p 8199:8199
-p 587:587
-p 7777:7777
-p 443:443
-e PUBLIC_IP=**...*
--restart always
whatsapp_proxy:1.0
