### ISSUE TITLE
https://faq.whatsapp.com/1299035810920553/?helpref=uf_share

### ISSUE THREAD

**Issue by MohamedKhairy220** [WhatsApp/proxy#290]
**Before reporting a bug, please see our FAQ in [FAQ.md](https://github.com/whatsapp/proxy/blob/main/FAQ.md)!**

**Comment by SHABI220** [comment]
[GITHUB-20230922-GitHubDataProtectionAgreement.pdf](https://github.com/user-attachments/files/16536088/GITHUB-20230922-GitHubDataProtectionAgreement.pdf)
