### ISSUE TITLE
Media Unavailable WhatsApp proxy  needs to be updated 

### ISSUE THREAD

**Issue by GabrielKidd** [WhatsApp/proxy#291]
#### Description
When attempting to send media files through the WhatsApp proxy, the media fails to be delivered, resulting in a "Media Unavailable" error. This issue affects the reliability and functionality of the proxy, particularly for media transmission.

#### Steps to Reproduce
1. Configure and run the WhatsApp proxy using the latest available image.
2. Attempt to send a media file (image, video, etc.) through the proxy.
3. Observe that the media fails to be delivered and an error message "Media Unavailable" is displayed.

#### Actual Behavior
Media files fail to be delivered, and an error message "Media Unavailable" is shown.

**Comment by dephea** [comment]
Same for me, but it works rather unstable. Works off and on using the same device. Also might work on one device and not work on the other, at the same time

**Comment by eozturk1** [comment]
@GabrielKidd, can you share which platform you are on? Has this recently started or were you having this issue before as well? Can you please confirm the proxy supports media as well?

**Comment by mvscode** [comment]
> @GabrielKidd, can you share which platform you are on? Has this recently started or were you having this issue before as well? Can you please confirm the proxy supports media as well?

Dear Dev：

The multimedia ports are not functioning for the proxy application, although the text（80/443） connection is work. 
The whatsapp proxy was successfully deployed on the machine in June, with ports 443 and 587 working normally. But without any modifications to the proxy, starting from August or possibly earlier, accessing text content port 443 works normally, but attempts to access multimedia through ports 587/7777 result in connection failures. 
After reinstalling the proxy and conducting other troubleshooting measures, the problem persists. Even when I deployed the proxy on a different machine, the aforementioned issues still exist. 
Furthermore, I've noticed that others have reported similar problems in the issue #281 about TLS , which you may find relevant for reference.

**Comment by ericlam918** [comment]
When using Android, both text and media can be sent successfully through the same proxy server. However, on iPhone, only text messages can be sent, while media fails to deliver. In the case of the older version of iOS WhatsApp, both text and media functions operate smoothly. Upon updating iOS WhatsApp, the functionality is reduced to text-only transmissions.

**Comment by dephea** [comment]
@eozturk1 Hello! Is there any update regarding this issue? Will this be fixed? Thank you in advance

**Comment by Kath-estrd** [comment]
Re: [WhatsApp/proxy] Media Unavailable WhatsApp proxy  needs to be updated  (Issue #291) (Re: [WhatsApp/proxy] Medios no disponibles. Es necesario actualizar el proxy de WhatsApp (problema n.° 291))

**Comment by eozturk1** [comment]
> When using Android, both text and media can be sent successfully through the same proxy server. However, on iPhone, only text messages can be sent, while media fails to deliver. In the case of the older version of iOS WhatsApp, both text and media functions operate smoothly. Upon updating iOS WhatsApp, the functionality is reduced to text-only transmissions.

We are aware of this issue and will issue a fix @dephea. Thank you for reporting!

**Comment by GabrielKidd** [comment]
> @GabrielKidd, can you share which platform you are on? Has this recently started or were you having this issue before as well? Can you please confirm the proxy supports media as well?

I am using the iOS platform. At the end of July, the proxy was working fine, but recently the issue of "Media Unavailable" has suddenly appeared. Neither port 7777 nor port 587 is working properly, while the chat port on 443 works well for sending and receiving text messages, but it cannot send images. I suspect it might be an issue with CA certificate authentication, but the proxy does not have the functionality to edit certificates.

**Comment by GabrielKidd** [comment]
> @GabrielKidd，您能分享一下您使用的平台吗？这是最近才出现的还是您以前也遇到过这个问题？您能确认代理也支持媒体吗？

I have tried both compiling the image myself and using the official Docker image, and the problem persists. It seems to have started after the recent update to iOS WhatsApp.
<img width="645" alt="Screenshot 2024-08-08" src="https://github.com/user-attachments/assets/6536ee61-54b2-4034-9b6a-501c6b575c6a">

**Comment by ericlam918** [comment]
Today, the iOS version of WhatsApp upgraded to 2.24.16.75, seemingly enabling the transmission of media files.

**Comment by GabrielKidd** [comment]
> Today, the iOS version of WhatsApp upgraded to 2.24.16.75, seemingly enabling the transmission of media files.

That’s correct! The latest iOS version of WhatsApp, 2.24.16.75, indeed allows the transmission of media files.

**Comment by eozturk1** [comment]
Great to see the issue has been resolved! Please update your apps if you are still having this issue!

**Comment by dephea** [comment]
Hello! I still got the issue with Media host not working. I experience it with both android and ios

**Comment by dephea** [comment]
@GabrielKidd @ericlam918 Hello guys, does it still work on your end? I got it working for a few days after updating my ios app but now it seems that the problem is occuring again

**Comment by GabrielKidd** [comment]
> @GabrielKidd @ericlam918 Hello guys, does it still work on your end? I got it working for a few days after updating my ios app but now it seems that the problem is occuring again
The current iOS version is 24.16.78.
Everything is working fine now, even if you don't set up a media port, you can still send and receive pictures.

**Comment by ericlam918** [comment]
My iOS version 2.24.16.78.
Still working fine now.

**Comment by dephea** [comment]
Thank you for feedback. Still doesn't work for me for some reason. 
I'm on 2.24.16.78 as well

**Comment by dephea** [comment]
![image](https://github.com/user-attachments/assets/31da0ffd-c1ed-4799-979c-13409b4f359e)

**Comment by GabrielKidd** [comment]
> ![image](https://private-user-images.githubusercontent.com/48135742/358144349-31da0ffd-c1ed-4799-979c-13409b4f359e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDUwNjEsIm5iZiI6MTcyMzcwNDc2MSwicGF0aCI6Ii80ODEzNTc0Mi8zNTgxNDQzNDktMzFkYTBmZmQtYzFlZC00Nzk5LTk3OWMtMTM0MDliNGYzNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZTAyMTFiOTBiYjFhMzc1ZmE1MDlhMmYxNGMyN2I3MmI5N2NmY2UzMWYyMTAyNGFmNmZiMjliMzVlOGRlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LARynZTRNVJqYCTW8bK5wc36vWHI9yycB_APEq2MGSo)

Your iOS version 2.24.16.78 is different from mine. I no longer have the 'Media' status option displayed.

**Comment by dephea** [comment]
@GabrielKidd 
Perhaps this is because your media proxy is working, hence it doesn't show an error. As far as I noticed just says "Connected" if both Chat and Media ports are working

**Comment by alexdatur** [comment]
can somebody help with media?
Use this config and chats works well on 443, but media dont work on 587 or 7777
docker run -d --name whatsapp-proxy \
  -p 80:80 \
  -p 8199:8199 \
  -p 587:587 \
  -p 7777:7777 \
  -p 443:443 \
  -e PUBLIC_IP=**.*.*.* \
  --restart always \
  whatsapp_proxy:1.0
