### ISSUE TITLE
[WARNING] config : log format ignored for

### ISSUE THREAD

**Issue by tyrion-sg** [WhatsApp/proxy#31]
Hey, after following the steps carefully, the following warning is shown. I am not able to connect via WhatsApp Proxy.

What is the issue here?

![image](https://user-images.githubusercontent.com/122086199/210966403-1c9849e7-e339-4701-b5f8-3ed67146d2dc.png)

**Comment by tyrion-sg** [comment]
I already deleted all the #PUBLIC_IP Lines from .cfg file

**Comment by slawlor** [comment]
That's fine, you can ignore that. We specifically disable logging so the proxy doesn't capture who's connecting to it, it's just haproxy saying that it's disabling logging for each input port.

**Comment by tyrion-sg** [comment]
> That's fine, you can ignore that. We specifically disable logging so the proxy doesn't capture who's connecting to it, it's just haproxy saying that it's disabling logging for each input port.

But I can't connect to the WhatsApp proxy, Powershell just crashes after those warnings

**Comment by tyrion-sg** [comment]
> > That's fine, you can ignore that. We specifically disable logging so the proxy doesn't capture who's connecting to it, it's just haproxy saying that it's disabling logging for each input port.
> 
> But I can't connect to the WhatsApp proxy, Powershell just crashes after those warnings

@slawlor
