### ISSUE TITLE
Trademark infringement complain from enf.whatsapp.2548904@enf-meta.com

### ISSUE THREAD

**Issue by LokikSoni-Dev** [WhatsApp/proxy#329]
A few month ago I developed any app Status Saver to save WhatsApp Status but I got 

Trademark Owner:
WhatsApp LLC

Complainant Email:
enf.whatsapp.2548904@enf-meta.com

Complainant Details:
The app uses the trademarks, banners, badges and logos of WhatsApp without authorization, including, but not limited to, the use of ley elements of WhatsApp's Famous Trademarked Logo in the app's icon. The developer’s use of WhatsApp's trademarks in app’s title and/or icon implies an association or other relationship that is neither authorized nor endorsed by WhatsApp.

I tried to contact them throw email but it has been 5 days but no reply from WhatsApp LLC.  I am ready to do all required changes in app. I have done lots of hard work to develop this app. Please help me out.

**Comment by eozturk1** [comment]
Hi!

This repo is specifically for proxy related issues and I am not familiar with the infringement complain process unfortunately. I'll close this task.
