### ISSUE TITLE
Driver

### ISSUE THREAD

**Issue by FarzadHZZ** [WhatsApp/proxy#33]
![IMG_20230106_135912](https://user-images.githubusercontent.com/44641593/210988423-f0d5197a-e4df-4fc1-bfb8-21dabd0d2f33.jpg)
Driver erorr

**Comment by hujiko** [comment]
Hey,

that seems to happen, because you already have another service listening on Port 80.

Only one service can listen on Port 80 at a time.
You would need to figure out, which service is listening on Port 80 and stop that service, or migrate it to another Port.

**Comment by FarzadHZZ** [comment]
I don't have anything with port 80 at all

**Comment by slawlor** [comment]
If it's windows you do have something listening (there's always a web server running [IIS]). You could try only mapping 1 of the ports, say 5222. There shouldn't be anything running on 5222. (Just remove all `-p` arguments except for that one).

And perhaps 8199 if you want statistics.
