### ISSUE TITLE
unable to prepare context: path "/path_to_cloned_repository/proxy/" not found  (please help)

### ISSUE THREAD

**Issue by vahidlol** [WhatsApp/proxy#34]
i'm keep getting this error while everything is fine on my great ocean server ! 

"unable to prepare context: path "/path_to_cloned_repository/proxy/" not foundآ"

please help me  out guys what did do wrong to get this message or what should i do to fix it ?!

اگه فارسی هم بگید ممنون میشم رفقا

**Comment by FarzadHZZ** [comment]
docker build ./proxy/ -t whatsapp_proxy:1.0
اینو تست کن

**Comment by localhoct** [comment]
read the instruction carefuly and dont miss any thing you should get ur answer

**Comment by vahidlol** [comment]
> docker build ./proxy/ -t whatsapp_proxy:1.0 اینو تست کن

تست کردم خطا میگیرم هنوز ! 
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/proxy/Dockerfile: no such file or directory

**Comment by vahidlol** [comment]
> read the instruction carefuly and dont miss any thing you should get ur answer

I did it step by step by unfortunately i get this error message , which seems to be a problem for some other users in here as well .

**Comment by FarzadHZZ** [comment]
> > docker build ./proxy/ -t whatsapp_proxy:1.0 اینو تست کن
> 
> تست کردم خطا میگیرم هنوز ! unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/proxy/Dockerfile: no such file or directory

docker build ./proxy/proxy/ -t whatsapp_proxy:1.0 اینو تست کن

**Comment by yasershop** [comment]
> docker build ./proxy/ -t whatsapp_proxy:1.0
> 
> اینو تست کن

نشد من امتحان کردم

**Comment by kazem3d** [comment]
اصلاً کلون کردی ریپو رو روی سرورت؟!

**Comment by FarzadHZZ** [comment]
> اصلاً کلون کردی ریپو رو روی سرورت؟!

راس میگه

**Comment by vahidlol** [comment]
> اصلاً کلون کردی ریپو رو روی سرورت؟!

با دستور 
git clone https://github.com/WhatsApp/proxy.git 

کلون کردم اگه اشتباه نباشه !

**Comment by ehsanghaffar** [comment]
Please clone this repo to your server and add its address to the docker command.

example:
```bash
cd /home
git clone https://github.com/WhatsApp/proxy/

docker build /home/proxy/proxy/ -t whatsapp_proxy:1.0
```

**Comment by vahidlol** [comment]
> Please clone this repo to your server and add its address to the docker command.
> 
> example:
> 
> ```shell
> cd /home
> git clone https://github.com/WhatsApp/proxy/
> 
> docker build /home/proxy/proxy/ -t whatsapp_proxy:1.0
> ```

Thanks a lot  Ehsan it actually worked and fixed my problem, would you mind  tell me to what to do next?!  i followed the next 

command as : docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0

 and i get some errors  like this :
 
 /
[NOTICE]   (20) : haproxy version is 2.6.7-c55bfdb
[WARNING]  (20) : config : log format ignored for proxy 'stats' since it has no log address.
[WARNING]  (20) : config : log format ignored for frontend 'haproxy_v4_http' since it has no log address.
[WARNING]  (20) : config : log format ignored for frontend 'haproxy_v4_https' since it has no log address.
[WARNING]  (20) : config : log format ignored for frontend 'haproxy_v4_xmpp' since it has no log address.
[ALERT]    (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:84] : 'server wa/g_whatsapp_net_5222' : could not resolve address 'g.whatsapp.net'.
[ALERT]    (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:88] : 'server wa_http/g_whatsapp_net_80' : could not resolve address 'g.whatsapp.net'.
[ALERT]    (20) : config : Failed to initialize server(s) addr.

**Comment by ehsanghaffar** [comment]
> > Please clone this repo to your server and add its address to the docker command.
> > example:
> > ```shell
> > cd /home
> > git clone https://github.com/WhatsApp/proxy/
> > 
> > docker build /home/proxy/proxy/ -t whatsapp_proxy:1.0
> > ```
> 
> Thanks a lot Ehsan it actually worked and fixed my problem, would you mind tell me to what to do next?! i followed the next
> 
> command as : docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0
> 
> and i get some errors like this :
> 
> / [NOTICE] (20) : haproxy version is 2.6.7-c55bfdb [WARNING] (20) : config : log format ignored for proxy 'stats' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_http' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_https' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_xmpp' since it has no log address. [ALERT] (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:84] : 'server wa/g_whatsapp_net_5222' : could not resolve address 'g.whatsapp.net'. [ALERT] (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:88] : 'server wa_http/g_whatsapp_net_80' : could not resolve address 'g.whatsapp.net'. [ALERT] (20) : config : Failed to initialize server(s) addr.


**Hi Vahid 👋🏻
Are you running this on a server in Iran?**

**Comment by vahidlol** [comment]
> > > Please clone this repo to your server and add its address to the docker command.
> > > example:
> > > ```shell
> > > cd /home
> > > git clone https://github.com/WhatsApp/proxy/
> > > 
> > > docker build /home/proxy/proxy/ -t whatsapp_proxy:1.0
> > > ```
> > 
> > 
> > Thanks a lot Ehsan it actually worked and fixed my problem, would you mind tell me to what to do next?! i followed the next
> > command as : docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0
> > and i get some errors like this :
> > / [NOTICE] (20) : haproxy version is 2.6.7-c55bfdb [WARNING] (20) : config : log format ignored for proxy 'stats' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_http' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_https' since it has no log address. [WARNING] (20) : config : log format ignored for frontend 'haproxy_v4_xmpp' since it has no log address. [ALERT] (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:84] : 'server wa/g_whatsapp_net_5222' : could not resolve address 'g.whatsapp.net'. [ALERT] (20) : config : [/usr/local/etc/haproxy/haproxy.cfg:88] : 'server wa_http/g_whatsapp_net_80' : could not resolve address 'g.whatsapp.net'. [ALERT] (20) : config : Failed to initialize server(s) addr.
> 
> **Hi Vahid 👋🏻 Are you running this on a server in Iran?**

Hi , no i'm running this on one digitalocean servers!

**Comment by vahidlol** [comment]
> > 
> 
> I think try another way. Use Docker-compose like this
> 
> ```shell
> cd /home
> git clone https://github.com/WhatsApp/proxy/
> cd /home/proxy/proxy/ops
> docker compose up -d
> ```
> 
> for see logs
> 
> ```shell
> docker compose logs
> ```

you are champion man !! it works finally ! i really appreciate you taking time to solve this.

**Comment by slawlor** [comment]
Closing issue as it looks like it's resolve. Thanks!

**Comment by Mamadgij** [comment]
> Please clone this repo to your server and add its address to the docker command.
> 
> example:
> 
> ```shell
> cd /home
> git clone https://github.com/WhatsApp/proxy/
> 
> docker build /home/proxy/proxy/ -t whatsapp_proxy:1.0
> ```
hi dear Ehsan
first i don't have any idea about servers and proxy but i want to make this for my family in iran. i tried a lot and used this one but unfortunately i got this msg 
"Command 'cdcd' not found, but can be installed with:
apt install cdcd
fatal: destination path 'proxy' already exists and is not an empty directory.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] missing "SSL_IP" build argument. Try adding "--build-arg SSL_IP=<VALUE>" to the command line 
WARN[0000] missing "SSL_DNS" build argument. Try adding "--build-arg SSL_DNS=<VALUE>" to the command line 
STEP 1/27: FROM haproxy:lts-alpine
Error: error creating build container: short-name "haproxy:lts-alpine" d"

and then i tried another one and got this msg

"Command 'cdcd' not found, but can be installed with:
apt install cdcd
fatal: destination path 'proxy' already exists and is not an empty directory.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: unknown shorthand flag: 'd' in -d"

could you please tell me how can i fix it?

**Comment by alimousavi21** [comment]
Error response from daemon: driver failed programming external connectivity on endpoint whatsapp_proxy (986c58c4969826e992b34da7035185f23567d4eee4ee9476fdadf6073682ec76): Bind for 0.0.0.0:80 failed: port is already allocated
من با این ارور مواجه شدم ، ممکنه کمک کنید؟



> > 
> 
> فکر کنم یه راه دیگه رو امتحان کن از Docker-compose به این صورت استفاده کنید
> 
> ```shell
> cd /home
> git clone https://github.com/WhatsApp/proxy/
> cd /home/proxy/proxy/ops
> docker compose up -d
> ```
> 
> برای مشاهده سیاهههای مربوط
> 
> ```shell
> docker compose logs
> ```

**Comment by ehsanghaffar** [comment]
> Error response from daemon: driver failed programming external connectivity on endpoint whatsapp_proxy (986c58c4969826e992b34da7035185f23567d4eee4ee9476fdadf6073682ec76): Bind for 0.0.0.0:80 failed: port is already allocated من با این ارور مواجه شدم ، ممکنه کمک کنید؟

خیلی واضح گفته که پورت 80 شما قبلا توسط یه سرویس دیگه داره استفاده میشه، شما هر پورت رو فقط به یه سرویس میتونین اختصاص بدین.
(احتمالا سایت روی سرور دارین یا یه سرویسی که پورت 80 رو استفاده میکنه)

Sorry @slawlor, You closed this issue but we continued it.
