### ISSUE TITLE
It doesn't work without VPN بدون فیلترشکن نمیاد

### ISSUE THREAD

**Issue by vargha1** [WhatsApp/proxy#35]
I checked the ports with open port checker, they were open, when i try to connect with vpn it always connects but it doesn't work without VPN

پورت هاش باز هست ولی بدون vpn کار نمیکنه راه حلی ندارید؟ برای چند نفر فرستادم اونا تونستن وصل بشن نت هامون هم یکی بود ولی خیلیا هم نتونستن وصل شن. کاری باید کرد؟

**Comment by aminroosta** [comment]
I can connect outside Iran, but my friends and family from Iran cannot.

The ports are open and functional, could there be something blocked at the haproxy level?

**Comment by RyAghaeifar** [comment]
Hi All, 

After updating iOS and WhatsApp, proxy still doesn't show up. Is there any solution? Thanks

**Comment by nghazali** [comment]
Please test it again considering the recent update ([random certification instead of selfsigned](https://github.com/WhatsApp/proxy/pull/97)). This should fix the problem.
