### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by tyrion-sg** [WhatsApp/proxy#39]
I get this error

![image](https://user-images.githubusercontent.com/122086199/211029573-a0b74f90-134a-4852-9dd5-e6e675c6b283.png)

How can I work around this? Please help, thank you

**Comment by slawlor** [comment]
You have something already running on 443. You essentially have 2 choices

1. Do not try and bind to 443 (HTTPS) which can be done by removing `-p 443:443` on the run command or in the docker compose mapping
2. Re-map to another port on your host, i.e. `-p 8443:443` or something like that. However the client is expecting 443 to have a secondary layer of encryption for now, so non-standard ports **for 443** are not currently supported. You can however safely remap 80 and 5222 as you see fit.

**Comment by tyrion-sg** [comment]
I do not understand, what should I run? Why is it crashing after the warnings? it does not help

**Comment by tyrion-sg** [comment]
Nothing works, all the ports give the same error

**Comment by tyrion-sg** [comment]
Still get the same error, help please

**Comment by tyrion-sg** [comment]
@slawlor ?

**Comment by luqmanzaceria** [comment]
Use `docker kill $(docker ps -q)` to kill all docker containers, this will deallocate your proxy host container from the port. Then you can rebuild the proxy host container with `docker build /path_to_cloned_repository/proxy/ -t whatsapp_proxy:1.0`

**Comment by tyrion-sg** [comment]
> 

After rebuilding I run into same issue

**Comment by slawlor** [comment]
Since you're on windows, it's potentially related to file line-endings. #72

**Comment by slawlor** [comment]
Please re-open this issue if it's still a problem. closing for now
