### ISSUE TITLE
Failed to connect to proxy

### ISSUE THREAD

**Issue by Mamadgij** [WhatsApp/proxy#43]
hi dear Sir/Madam
first i don't have any idea about servers and proxy but i want to make this for my family in iran. i tried a lot and used this one but unfortunately i got this msg after use this 

```
cd /home
git clone https://github.com/WhatsApp/proxy/
cd /home/proxy/proxy/ops
docker compose up -d

```
 :
fatal: destination path 'proxy' already exists and is not an empty directory.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: unknown shorthand flag: 'd' in -d

could you please tell me how can i fix it?

**Comment by mohsenhatami96** [comment]
Hi @Mamadgij,

First of all, please run this command to delete the previous clone:
`rm -rf /home/proxy`

For the other errors:
1. Have you installed Docker on your server?
2. Have you tried to build the image? This is how you can do it:
[Build the proxy host container](https://github.com/WhatsApp/proxy#3-build-the-proxy-host-container)

**Comment by Mamadgij** [comment]
Hi dear @mohsenhatami96 

Thanks for your help
After I installed Docker on my server, I checked Docker version by this code :
`docker version
`
and got this msg : 
"Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64"

and tried to build the image according to page that you sent. Unfortunately, its not working
I used this code
`docker build /path_to_cloned_repository/proxy/ -t whatsapp_proxy:1.0`

and got this message :

"Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: context must be a directory: "/path_to_cloned_repository/proxy""

Could you please tell me what's wrong?

**Comment by Mamadgij** [comment]
Hi @mohsenhatami96 

It works.
thanks for your support.
