### ISSUE TITLE
Proxypass from Nginx

### ISSUE THREAD

**Issue by SasukeFreestyle** [WhatsApp/proxy#45]
As title says.

Is it possible to proxypass the Whatsapp Proxy from Nginx.

This is to prevent active probing and also hide the proxy service.

Does anyone have a working Nginx config for this?

**Comment by slawlor** [comment]
This isn't an HTTP proxy, so reverse proxying isn't going to help here. It's a pure TCP proxy, the only "probing" you can do is to do a port-scan.

**Comment by SasukeFreestyle** [comment]
Gotcha, Thanks, Issue can be closed.
