### ISSUE TITLE
Error when making container 

### ISSUE THREAD

**Issue by arno1415** [WhatsApp/proxy#48]
I get this error when making the container:

 [ 5/14] RUN chmod +x /usr/local/bin/generate-certs.sh &&     /usr/local/bin/generate-certs.sh &&     mkdir --parents /etc/haproxy/ssl/ &&     mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem &&     chown -R haproxy:haproxy /etc/haproxy/:
executor failed running [/bin/sh -c chmod +x /usr/local/bin/generate-certs.sh &&     /usr/local/bin/generate-certs.sh &&     mkdir --parents /etc/haproxy/ssl/ &&     mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem &&     chown -R haproxy:haproxy /etc/haproxy/]: exit code: 127

Does anyone know a fix for this or what I may have done wrong?

**Comment by sabzipolo705** [comment]
I had the same issue but solved it by changing the end-of-line (EOL) sequence from CRLF (Windows) to LF (Unix) in the generate-certs.sh file. You have to open \proxy\src\generate-certs.sh in a text editor that allows changing the EOL (like notepad++, VS Code, etc.), click on CRLF on the bottom right corner and change it to LF, save the file and run the docker build command again. Hope this helps!

**Comment by ahmadlou** [comment]
/bin/sh: /usr/local/bin/set_public_ip_and_start.sh: not found
