### ISSUE TITLE
problem in public ip

### ISSUE THREAD

**Issue by salarkarimi98** [WhatsApp/proxy#54]
Hi there I got this error when running container
ww@whatsapp:~/proxy/proxy$ docker run -it -p 80:80 -p 443:443 -p 5222:5222 -p 8080:8080 -p 8443:8443 -p 8222:8222 -p 8199:8199 whatsapp_proxy:1.0
[PROXYHOST] No public IP address was supplied as an environment variable.
[PROXYHOST] Public IP address (<?xml version="1.0" encoding="utf-8"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Code>ResourceNotFound</Code>
    <Message>The specified resource does not exist.</Message>
    <Details>'latest' isn't a valid resource name.</Details>
</Error>) in-place replacement occurring on /usr/local/etc/haproxy/haproxy.cfg
sed: unmatched '/'
/home/haproxy/certs /
----------------------------
| SSL Certificate Generation |
----------------------------
------------------------------------------
also I changed the config file and comment the public ip but didn't work
I commented lines that start with bind
  #PUBLIC_IP

  #bind ipv4@*:80
  #bind  ipv4@*:8080 accept-proxy

  default_backend wa_http

frontend haproxy_v4_https
  maxconn 27495
  #PUBLIC_IP

  #bind  ipv4@*:443 ssl crt /etc/haproxy/ssl/proxy.whatsapp.net.pem
  #bind  ipv4@*:8443 ssl crt /etc/haproxy/ssl/proxy.whatsapp.net.pem accept-proxy

  default_backend wa

frontend haproxy_v4_xmpp
  maxconn 27495
  #PUBLIC_IP

  #bind  ipv4@*:5222
  #bind  ipv4@*:8222 accept-proxy

**Comment by salarkarimi98** [comment]
> Revert your changes and add this line to you your Dockerfile at line 14: `ENV PUBLIC_IP=YOUR_SERVER_IP` Replace `YOUR_SERVER_IP` with your server's public IP, rebuild the Docker image, and try again.

thank you @mohsenhatami96 
solved

**Comment by salarkarimi98** [comment]
thank you @mohsenhatami96

**Comment by ehsanshams** [comment]
Hi Guys,

I managed to setup a proxy server as of you explained here. Now the problem is although it shows connected, it is not working inside Iran. Although working in Germany.

**Comment by yourAnonDH** [comment]
@mohsenhatami96 thanks!
