### ISSUE TITLE
Iran: tested on Windows 10 , works for some and doesn't for others 

### ISSUE THREAD

**Issue by deimosdamocles** [WhatsApp/proxy#58]
Used a Windows 10 server outside of Iran (details shared further below). Some friends in Iran could connect via port 443, but some couldn't connect at all. Wifi generally works better, on mobile data it depends on who the phone provider is and where they are located! The fact is that the authorities have significantly decreased the upload and download speed, **esp.** the upload speed, to and from any server outside of a certain white list (that white list includes servers such as those using googlemeet, one of the very few ways remaining for people to communicate with abroad) . Therefore any voice or image takes a loooooong time to arrive (a 5sec voice sent from Iran took 40mins to arrive!).

Also, please try to make it a bit more like Telegram ... what is this ?! giving literally the IP without any protocol!? that can be blocked in a split second by authorities if the IP address gets found out. Everyone in Iran would have to depend on someone they know abroad personally, and not every Iranian has acquaintances abroad! Setting it up like `TelegramMessenger/MTProxy` should allow communities to share their proxies more safely.

P.S. For people who want to do this on Windows 10 (this should also work on windows 11):

First make sure you got WSL 2 . And while you install Docker, make sure the WSL 2 based engine is used; it's the default when installing docker on windows, but if you don't know if it's active or not, open your docker and go to Settings-->General and check "Use the WSL 2 based engine". 

Now, be careful to git clone the repo into your WSL `home/<your_username>` directory, and then don't forget to delete any `#PUBLIC_IP` mentions (there are three of them as of now) in the `proxy/src/proxy_config.cfg` file using a WSL editor (nano / vim or gedit if you got windows 11).  Do not try to do any of these in a Windows directory or using a Windows text editor, as it will haunt you (there are some text encoding issues when you use a Windows directory). 

But then after that you can docker build and run on Powershell using the repository in the WSL;  to actually tell docker on Windows to use the repo in WSL, it's better to map WSL to a network drive . Go to your file explorer, right click on "This PC" and select map network drive. Then choose any letter for the drive, say Z,  and for the Folder enter : `\\wsl$\Ubuntu-X` for whatever Ubuntu version X your WSL is running (e.g. `X = 18.04`).

Then you just enter `docker build Z:\home\<your_username>\proxy\proxy\ -t whatsapp_proxy:1.0` in your Powershell and then the docker run command. (and don't  forget the basics! do the port forwarding in your router for ports 80, 443, 5222, (and there are three more which really don't work even when I tested them myself!)).

**Comment by mohsen202** [comment]
Tanks
