### ISSUE TITLE
unable to prepare context: path "/path/to/git/repo/" not found

### ISSUE THREAD

**Issue by u10if** [WhatsApp/proxy#6]
when i run  docker build /path/to/git/repo/ -t whatsapp_proxy:1.0 its says unable to prepare context: path "/path/to/git/repo/" not found
how should i do???

**Comment by slawlor** [comment]
`/path/to/git/repo/` is a sample of where you've checked out the repository. You use the full path on your system which is where you cloned the repository. 

For example if you clone to 

```
git clone https://github.com/WhatsApp/proxy.git ./whatsapp_proxy
```

then the path would be `./whatsapp_proxy`

**Comment by u10if** [comment]
Okay thank you, but now I clone to whatsapp_proxy, and then when run 
` docker build /whatsapp_proxy/ -t whatsapp_proxy:1.0  `
again says : 
unable to prepare context: path "/whatsapp_proxy/" not found :(
