### ISSUE TITLE
Docker is running , why when I try to use a proxy on whatsapp it doesn't work?

### ISSUE THREAD

**Issue by dasx000** [WhatsApp/proxy#61]
"Container whatsapp_proxy  Running  "
Docker is running , why when I try to use a proxy on whatsapp it doesn't work?
always connecting.

**Comment by gharibe** [comment]
where is the server running? are you using a cloud provider like AWS? you need to add inbound rules and allow connection on those ports.

**Comment by gharibe** [comment]
if you are doing this on a home lab/server you need add to add port forwarding on your router.

**Comment by FarzadRoghani** [comment]
Hello, I am going to use my laptop as a server, I have already opened a port on my router (using my laptop ip address and 8080 as the port) . Is the procedure different?

**Comment by maryyam** [comment]
> if you are doing this on a home lab/server you need to add port forwarding on your router.

Could you please explain it more in details please?

**Comment by gharibe** [comment]
> > if you are doing this on a home lab/server you need to add port forwarding on your router.
> 
> Could you please explain it more in details please?

The process is different depending the model of your router. basically you need to open the port on your router and allow traffic to reach the docker container. if you are not familiar wit the process I don't recommend opening ports on your home router.

**Comment by gharibe** [comment]
> Hello, I am going to use my laptop as a server, I have already opened a port on my router (using my laptop ip address and 8080 as the port) . Is the procedure different?

try other ports if 8080 is not working, also AWS offers a free tier for a year that you can sign up for. if that is an option for you. that way you don't have to mess with your router and open ports on it.

**Comment by dasx000** [comment]
I am using a server from DO

**Comment by dasx000** [comment]
my port is already open

**Comment by dasx000** [comment]
http://157.245.51.0:8199/

**Comment by dasx000** [comment]
Is it true that if connected, you can access WhatsApp without internet?

**Comment by viatk** [comment]
[> Is it true that if connected, you can access WhatsApp without internet?

No it's not true, the proxy would just redirect the connection to WhatsApp, you still need the internet. 
Looks like this issue is reported as misunderstanding, closing it.](url)
