### ISSUE TITLE
Error while making container

### ISSUE THREAD

**Issue by vigilant24** [WhatsApp/proxy#64]
I get this error when making the container:

 [ 5/14] RUN chmod +x /usr/local/bin/generate-certs.sh &&     /usr/local/bin/generate-certs.sh &&     mkdir --parents /etc/haproxy/ssl/ &&     mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem &&     chown -R haproxy:haproxy /etc/haproxy/:
#9 3.378 /bin/sh: /usr/local/bin/generate-certs.sh: not found
------
executor failed running [/bin/sh -c chmod +x /usr/local/bin/generate-certs.sh &&     /usr/local/bin/generate-certs.sh &&     mkdir --parents /etc/haproxy/ssl/ &&     mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem &&     chown -R haproxy:haproxy /etc/haproxy/]: exit code: 127

Does anyone know a fix for this or what I may have done wrong?

**Comment by pedramfeyz** [comment]
> I get this error when making the container:
> 
> ## [ 5/14] RUN chmod +x /usr/local/bin/generate-certs.sh && /usr/local/bin/generate-certs.sh && mkdir --parents /etc/haproxy/ssl/ && mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem && chown -R haproxy:haproxy /etc/haproxy/:
> #9 3.378 /bin/sh: /usr/local/bin/generate-certs.sh: not found
> executor failed running [/bin/sh -c chmod +x /usr/local/bin/generate-certs.sh && /usr/local/bin/generate-certs.sh && mkdir --parents /etc/haproxy/ssl/ && mv /certs/proxy.whatsapp.net.pem /etc/haproxy/ssl/proxy.whatsapp.net.pem && chown -R haproxy:haproxy /etc/haproxy/]: exit code: 127
> 
> Does anyone know a fix for this or what I may have done wrong?

I got the same issue, I'm trying to build the docker image on windows machine

**Comment by nariman-13** [comment]
Im also having the same issue trying to build a docker image on a windows machine. I have also done it on linux OS but the same issue...
anyone know how to fix this?

**Comment by sabzipolo705** [comment]
I had the same issue but solved it by changing the end-of-line (EOL) sequence from CRLF (Windows) to LF (Unix) in the generate-certs.sh file. You have to open \proxy\src\generate-certs.sh in a text editor that allows changing the EOL (like notepad++, VS Code, etc.), click on CRLF on the bottom right corner and change it to LF, save the file and run the docker build command again. Hope this helps!
