### ISSUE TITLE
443 port already used

### ISSUE THREAD

**Issue by hiradsajde** [WhatsApp/proxy#65]
hello 
i wanna create whatsapp proxy but in my personal server i installed nginx-proxy-manager for reverse proxies , and nginx needs 443 port
so i get this error : 
Error response from daemon: driver failed programming external connectivity on endpoint vigilant_rhodes (daa751c5cf24ea86c056c27b8ba3533838d1172ce8b5434ae2150cce2fe9b2dd): Bind for 0.0.0.0:443 failed: port is already allocated.
how can i solve it?

**Comment by Djegha** [comment]
ياودي مكانش منها راهم يخرطو برك

**Comment by opirani** [comment]
@hiradsajde 
There are 3 different pairs, with different communication protocols as below:

80: Standard web traffic (HTTP) 
443: Standard web traffic, encrypted (HTTPS)
5222: Jabber protocol traffic (WhatsApp default)

8080: Standard web traffic (HTTP) with PROXY protocol expected
8443: Standard web traffic, encrypted (HTTPS) with PROXY protocol expected
8222: Jabber protocol traffic (WhatsApp default) with PROXY protocol expected

just use other pairs without 443:
> docker run -it -p 80:80 -p 5222:5222 -p 8080:8080 -p 8222:8222 whatsapp_proxy:1.0

and set the the proxy with PORT on the Client Side as -> "xxx.xxx.xxx.xxx:5222" or "xxx.xxx.xxx.xxx:80"

**Comment by slawlor** [comment]
This is addressed in the FAQ now around re-mapping ports (point number 4). Closing issue.
