### ISSUE TITLE
Failed to read dockerfile on Mac

### ISSUE THREAD

**Issue by faramarza** [WhatsApp/proxy#68]
Running on Mac Monteray 12.5
Cloned repo
Docker already installed
when running docker build I receive
=> [internal] load build definition from Dockerfile                                                                                                                                                 0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1420828109/Dockerfile: no such file or directory

**Comment by abubakrsiddq** [comment]
Could you provide the docker build command that you are running and a output of `ls` command in that directoory

**Comment by faramarza** [comment]
I believe I solved it. The repo creates two directories called proxy, one below the other one. The docker command  "docker build /path_to_cloned_repository/proxy/ -t whatsapp_proxy:1.0" only has one proxy in the path. I re-ran with
docker build /path_to_cloned_repository/proxy/proxy/ -t whatsapp_proxy:1.0 and it worked.
