### ISSUE TITLE
HAProxy UI is missing inline css styles 

### ISSUE THREAD

**Issue by eshirvana** [WhatsApp/proxy#8]
not much to say ,  the css style is missing from UI :

![image](https://user-images.githubusercontent.com/72626662/210861725-9cb85af3-e6fe-437f-b183-b3569cd237be.png)

**Comment by eshirvana** [comment]
I see there is a image with a newer version of haproxy , maybe its addressed there already??

**Comment by slawlor** [comment]
Feel free to update the image tag in the Dockerfile and simply re-build to try if you wish! We're currently pointing at the LTS release which I think we'll stay at to avoid risking any other problems popping up for now, but if you want to run a pre-release or non-LTS that's completely fine. I will say we've seen the missing CSS for a long time (many versions) so I would be surprised if they fixed it, but you're welcome to open an issue to HAProxy as well to fix it!

Thanks!

**Comment by slawlor** [comment]
Closing as this is an HAProxy problem not us
