### ISSUE TITLE
Issue hosting Whatsapp proxy in Kubernetes 

### ISSUE THREAD

**Issue by gary-RR** [WhatsApp/proxy#82]
Hi,
I tried to host this in Kubernetes (private cloud) but pod fails (see complete logs below). A couple of things jump out:
1- Why does it require public IPs? For testing purposes, I think you should allow private IPs.
2- "[PROXYHOST] Failed to retrieve public ip address from AWS URI within 2s" does this only work on AWS?
3-  Socket binding fails due to permission errors "[ALERT]    (20) : Binding [/usr/local/etc/haproxy/haproxy.cfg:59] for frontend haproxy_v4_http: cannot bind socket (Permission denied) for [0.0.0.0:80]"

Please note that I did not use helm chart as it seems the instructions are still under construction and the proxy charts are missing on this page "https://artifacthub.io/packages/search?repo=WhatsApp"

Thanks!

****************************************************Logs************************************************************
kubectl logs whatsapp-proxy-v1-5768548ffb-7pg6b

[PROXYHOST] No public IP address was supplied as an environment variable.
[PROXYHOST] Failed to retrieve public ip address from AWS URI within 2s
/home/haproxy/certs /
----------------------------
| SSL Certificate Generation |
----------------------------

--> Certificate Authority
====> Generating new CA key ca-key.pem
====> Generating new CA Certificate ca.pem
-----BEGIN CERTIFICATE-----
MIIDHzCCAgegAwIBAgIUP35rl3DZrlqdRx+IclhW6W3cYWgwDQYJKoZIhvcNAQEL
BQAwHjEcMBoGA1UEAwwTd2hhdHNhcHAuc2VsZnNpZ25lZDAgFw0yMzAxMDgxOTQ0
MTdaGA8yMTIyMTIxNTE5NDQxN1owHjEcMBoGA1UEAwwTd2hhdHNhcHAuc2VsZnNp
Z25lZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKF8Cifsi7qWNIuQ
TeAhRlNfNEAAr+ZdhrvGBUo1ZUWKVcbmw0JxYZSeEOx4CTWRZ3z02FnZ/HYRk2rF
UWklUwkR7sQ7uvnyrjDdOb/OLSpbMllFt9+DFz5BcTztsMYOUPk6/3yDt3/xOpGu
ZuESorMAnq7BEnKgFlpC831IT+7OtajESdXREa9Yi/DGHgnLUsWErKRd3TObD8E8
yTTa/3FyRatAZ6SfSt+9VSExmVgiZtllO4Lz0+gnokAcEolMo5xi+PlE7+D6De22
JK+NHjETTEmKbcDRWo3D3jSHG7Df7OE7FDkWZ4yGCW+iffW9tnYRgsuWUXhsLEEl
00WCzjUCAwEAAaNTMFEwHQYDVR0OBBYEFG5AKz/c3YwMFYXS8krQT58l9nxPMB8G
A1UdIwQYMBaAFG5AKz/c3YwMFYXS8krQT58l9nxPMA8GA1UdEwEB/wQFMAMBAf8w
DQYJKoZIhvcNAQELBQADggEBAGrhbxh7sGdWSivYqoCfAcvK0LmfAR+g1ATEiVc8
f3EFWEsHQX1/4kJWr7Dv6iuAKo4zfdF9GUTb1tGMX/NXxd0C75b0dBmDzh1tJXBS
sE3DspV0JOgCS0Lm4RtPs85dQDjiNiqu36lWHHvxthJjpY+ZtuikzM+CwYAHeFJn
kiQsc9lcqZhVz8wRJkx1P5e8cadGbueZ93jEu/2AzflW6LJ+z9XD0FTpG0TXBQf3
jgJzoncOWR59nsHIrN6d1KUEtDC6JQw1So/QiDRE/Ols3IV0vTTvTnaFleg1vfyy
1DPqJaRfjcac3PYkbSaBlgJX0RVjQbSCBBLxjYAOC7YQ5rw=
-----END CERTIFICATE-----
====> Generating new config file openssl.cnf
====> Generating new SSL KEY key.pem
====> Generating new SSL CSR key.csr
====> Generating new SSL CERT cert.pem
Certificate request self-signature ok
subject=CN = proxy.whatsapp.net
====> Generating SSL CERT / KEY COMBO proxy.whatsapp.net.pem
Certificate generation completed.
/
[NOTICE]   (20) : haproxy version is 2.6.7-c55bfdb
[ALERT]    (20) : Binding [/usr/local/etc/haproxy/haproxy.cfg:59] for frontend haproxy_v4_http: cannot bind socket (Permission denied) for [0.0.0.0:80]
[ALERT]    (20) : Binding [/usr/local/etc/haproxy/haproxy.cfg:68] for frontend haproxy_v4_https: cannot bind socket (Permission denied) for [0.0.0.0:443]
[ALERT]    (20) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.

**Comment by slawlor** [comment]
> 1- Why does it require public IPs? For testing purposes, I think you should allow private IPs.

We don't explicitly require them, but it cleans up logging and some reporting. However it's not necessary and you can delete the #PUBLIC_IP statements in the haproxy configuration file

> 2- "[PROXYHOST] Failed to retrieve public ip address from AWS URI within 2s" does this only work on AWS?

No it works on any host, but there's a built-in attempt to get your ip from AWS for some helpful automation. You can ignore it

> 3- Socket binding fails due to permission errors "[ALERT] (20) : Binding [/usr/local/etc/haproxy/haproxy.cfg:59] for frontend haproxy_v4_http: cannot bind socket (Permission denied) for [0.0.0.0:80]"

Sounds like you aren't running as an admin or have something listening on :80?

**Comment by gary-RR** [comment]
Many thanks for your response and also for creating this, much appreciated! 

Based on your tip, I set the "securityContext" to root for the container in the deployment script and it worked:
securityContext:
          runAsUser: 0
