### ISSUE TITLE
Does not work in China

### ISSUE THREAD

**Issue by Christer-Ekholm** [WhatsApp/proxy#85]
I needed VPN to make my proxy work. Architecture would need to be redesigned so that all traffic goes through port 443.

**Comment by slawlor** [comment]
In the about section, this proxy only supports the default connection + chat. Currently media and VoIP are not supported through the proxy.

**Comment by Christer-Ekholm** [comment]
Whatsapp cannot connect successfully to proxy in China at all. Not related to media or Voip.

**Comment by ydagnhienil** [comment]
+1 
In Iran the same. Any Idea how they recognize and block it? Maybe we can change some parameter to get it functional.
With a new subject for selfsigned cert and new port, I've testet without any success.

Since it is working with VPN I guess China and Iran are somehow blocking the traffic.

Any Idea how they can block it?

**Comment by Christer-Ekholm** [comment]
I would redesign so that all data is routed via port 443. I do not think there is any easy fixes to this.  I  think currently blocking is easy because WeChatpptries to use other ports than 80 and 443.

**Comment by ydagnhienil** [comment]
I guess you are correct. I suppose somebody from WhatsApp should say his opinion about it too.

**Comment by GewoonJaap** [comment]
Are my proxies also blocked? https://whatsapp-proxy.com

**Comment by Christer-Ekholm** [comment]
Thanks lot. Seems that specifying port will help. I tested these with ios and worked without VPN

141.148.228.97:82
68.183.8.87:80
51.14.190.56:5222

**Comment by GewoonJaap** [comment]
Niceee! This works in Iran or any other country that blocks whatsapp?

**Comment by gary-RR** [comment]
@Christer-Ekholm @ydagnhienil, curious if you guys set up your proxies in China and Iran respectively, or outside the country?

**Comment by GewoonJaap** [comment]
> 

Mine are from The Netherlands and UK

**Comment by gary-RR** [comment]
@GewoonJaap  Yes, that's what I wanted to verify. Curious how they detect that it is a WhatsApp proxy because the traffic especially on ports 80 and 443 should look like ordinary traffic and for sure they wouldn't know the proxy IP addresses.

**Comment by xidnif** [comment]
> 

I am asking a few people to test and report back.

**Comment by GewoonJaap** [comment]
@gary-RR That's very strange indeed. Because both ports are the standard for web traffic.. And traffic on both ports should be encrypted by WhatsApp + the local proxy SSL cert (prob only on 443??)

**Comment by GewoonJaap** [comment]
I guess it's just TCP traffic right? No http(s) traffic. Because I wanted to try hide my proxy behind a Cloudflare Tunnel/setup a Cloudflare worker, but only possible with http(s) traffic afaik

**Comment by Christer-Ekholm** [comment]
I set my proxy to Azure cloud north Europe. It worked when I enabled VPN but did not work without it. So I am pretty sure that China great firewall block it.

**Comment by GewoonJaap** [comment]
> I set my proxy to Azure cloud north Europe. It worked when I enabled VPN but did not work without it. So I am pretty sure that China great firewall block it.

What happens if you start a little webserver, can you reach that one or also blocked? Maybe the block Azure IPs?

**Comment by xidnif** [comment]
Interestingly enough, out of the following 3, two worked in Iran. (one user, mobile data, no VPN)

YES 141.148.228.97:82
NO  68.183.8.87:80
YES 51.14.190.56:5222

I am surprised because port 80 should be more likely to work. Is it the DO server that's blocked? Will add more observations as they come in.

**Comment by gary-RR** [comment]
@xidnif how about 443?

**Comment by xidnif** [comment]
@gary-RR Can you give me a working server that offers 443? I haven't gotten around to set up one yet.

**Comment by gary-RR** [comment]
@xidnif, text WhatsApp me on 612-814-2418 and I'll share it with you as it is my Router's public IP address and I don't want to publicize it.

**Comment by GewoonJaap** [comment]
68.183.8.87:443 is up and running @xidnif it has a custom CN name

**Comment by GewoonJaap** [comment]
141.148.228.97:443 now also supports SSL

**Comment by Christer-Ekholm** [comment]
141.148.228.97:443  does not work

**Comment by GewoonJaap** [comment]
@Christer-Ekholm can you try again?

**Comment by Christer-Ekholm** [comment]
works now

**Comment by GewoonJaap** [comment]
Okay that's interesting.
![Screenshot_20230109-201948](https://user-images.githubusercontent.com/33700526/211390177-7414e5da-1e8b-4ee9-b9bb-9ba2f2aa07cb.png)
So change that to something random and it works

**Comment by xidnif** [comment]
@GewoonJaap 64.227.75.24:82 did not work either. 

141.148.228.97:443 didn't work either.

**Comment by GewoonJaap** [comment]
@xidnif Hmmff okay.. Very strange behaviour

**Comment by xidnif** [comment]
> Hmmff okay.. Very strange behaviour

I asked them to confirm that 82 still works. Also checking with other ISPs. I may be delayed in reporting back due to day job!

**Comment by GewoonJaap** [comment]
No problem! @xidnif Thanks for helping everyone out ☺️

Tomorrow I will try deploy a few more servers on Oracle (they have an amazing free tier!) And Google Cloud. Let's see if Google is blocked or not

**Comment by Christer-Ekholm** [comment]
I will tests again tomorrow and try modify my own server CN

**Comment by xidnif** [comment]
I am using Oracle as well. They seem to be working better in Iran. DO is hit or miss. Will collect some more data and report back.

**Comment by GewoonJaap** [comment]
@Christer-Ekholm Maybe we also have to change the CA_SUBJECT? the one that defaults to WhatsApp.selfhosted or something like that. Don't know what that is used for

**Comment by xidnif** [comment]
Thank you all for working on this. Would someone be able to put together a list where folks can enter their observations? Something like an airtable?

**Comment by gary-RR** [comment]
@GewoonJaap There is also an "export CA_SUBJECT="whatsapp.selfsigned" that may be a good idea to rename as well to remove any references to WhastApp.

**Comment by Christer-Ekholm** [comment]
I have two docker images. One with default certificate subjects and another with modifications
export CA_SUBJECT="ceproxy.selfsigned"
export SSL_SUBJECT="proxy.ceproxy.net"
and in China network I can only connect to modified one

**Comment by ydagnhienil** [comment]
I've setup a server in DigitalOcean with modified cert and port: `68.183.70.255:5432`. The user from Iran are reporting, that they can not connect to it.
Could it be, that Iran is blocking DigitalOcean by default, due to the cheap servers, which everybody want to use as VPN?

**Comment by Christer-Ekholm** [comment]
68.183.70.255:5432 works China

**Comment by ydagnhienil** [comment]
Then Iran is blocking harder than China. I don't have any other clarification.

**Comment by Christer-Ekholm** [comment]
I am not familiar when to close guthub Issues. To me it looks that following randomising would fix China issue
```
export SSL_SUBJECT="`openssl rand -hex 12`.net"
export CA_SUBJECT="`openssl rand -hex 12`.selfsigned"
echo $SSL_SUBJECT 
7b3db029798f16709115b0df.net
echo $CA_SUBJECT 
a3b415761b1438df0ac61255.selfsigned
```
Should I close this issue now or wait Pull request what will merge random subjects to certificates?

**Comment by GewoonJaap** [comment]
@Christer-Ekholm Please make a pull request, this way everyone has a working proxy for China :)

**Comment by GewoonJaap** [comment]
It would be even cooler if we could also randomize the .net part (Array with .com, .net, .org, .gov etc etc?)

**Comment by ydagnhienil** [comment]
@gary-RR I have a one proxy by Digitalocean which is not working in Iran too. Seems they block all the IP of this provider.
the one which you've provided by Oracle is working in Iran on iPhone but not on Android: `141.148.228.97:82`.    
Any Idea why?

**Comment by gary-RR** [comment]
@yahoo.com, it was @GewoonJaap's server. The only thing I can think of is that since port 82 is not SSL, they may be scanning the payload and figuerout it is related to WhatsApp. I think it is safer to use SSL (443). They will be able to block IPs but they won;t be able to read the content.

**Comment by gary-RR** [comment]
@Christer-Ekholm I think everyone who will be providing the proxy should set their own cert's SSL_SUBJECT and CA_SUBJECT to random strings and not pull into git, otherwise the government ciber thugs can easily see those changes and block them. I think this info regarding the change to cert subjects should go to the developer guide.

**Comment by gary-RR** [comment]
@slawlor, are VOIP and media support in the road map for future versions? Thanks.

**Comment by slawlor** [comment]
> @slawlor, are VOIP and media support on the road map for future versions? Thanks.

Media is definitely on our roadmap, but VoIP has many technical challenges related to the way we handle data and the fact most of it is UDP. To route that, we'd be looking close to a full VPN which if we give a spec (say `openvpn`) or people just buy a VPN service it's the same pretty much, so we are likely not going to be investing much to proxy VoIP at this time.

**Comment by dgoryeo** [comment]
> I am not familiar when to close github issues. To me it looks that following randomising would fix China issue
> 
> ```
> export SSL_SUBJECT="`openssl rand -hex 12`.net"
> export CA_SUBJECT="`openssl rand -hex 12`.selfsigned"
> echo $SSL_SUBJECT 
> 7b3db029798f16709115b0df.net
> echo $CA_SUBJECT 
> a3b415761b1438df0ac61255.selfsigned
> ```
> 
> Should I close this issue now or wait Pull request what will merge random subjects to certificates?

@Christer-Ekholm , would you have a fork with your changes for others to use? I think that might be faster workaround for the community than waiting for the merge.

**Comment by k10halifa** [comment]
Peace be upon you, I have a question, is VPN working for calls or not?

**Comment by Maldo365** [comment]
Porta mídia ? Porta conversar ? Alguém proxy
