### ISSUE TITLE
کانال تلگرام پروکسی واتساپ آماده

### ISSUE THREAD

**Issue by Aliasqarnia** [WhatsApp/proxy#90]
https://t.me/+Evox3E_Im543YTI0
#

**Comment by GewoonJaap** [comment]
https://whatsapp-proxy.com I am hosting these. Planning on making an API and adding some proxies that rotate their ips atleast once a day

**Comment by alirezabalsa** [comment]
سلام هیچ کدام وصل نمیشه چه فایده دارهه

**Comment by GewoonJaap** [comment]
Also could you check if port 7070 on the GardenSnakes proxies work in your browser? For example http://141.148.228.97:7070/ping should return a response that the server is up

**Comment by alirezabalsa** [comment]
سلام ممنونم از رهنمایی باز هم ارور میده
