### ISSUE TITLE
Cloudflare Tunnel

### ISSUE THREAD

**Issue by GewoonJaap** [WhatsApp/proxy#91]
Does port 80 and 443 of g.whatsapp.net use the http(s) protocol or is it TCP? Because I was wondering if I could deploy a bunch of Cloudflare workers to act as a reverse proxy, but Cloudflare workers are HTTP(S) based...

**Comment by slawlor** [comment]
Please see the new FAQ. We are TCP, not HTTP so you can't put it behind HTTP proxies.
