### ISSUE TITLE
This sucks, for a myriad of reasons...

### ISSUE THREAD

**Issue by abiusx** [WhatsApp/proxy#98]
1. This is just a shell around HAProxy. Why not just provide the HAProxy config, instead of marking this as a "WhatsApp proxy"?
I suppose this only supports text (no VoIP or media)  exactly because it's a HAProxy.
2. Why all the elaborate steps of building the docker container? Couldn't you guys just push the docker image and have people use that instead? It's not like there's much to build either...
3. HAProxy has been inspected and blocked to oblivion by Iranian filtering. Considering this whole project was pushed due to Iranian WhatsApp blockage, why didn't you guys even test it first? Any HAProxy server is going to be saturated by dangling connections coming from the Iranian origin and then being dropped. HAProxy uses TCP and meaningful sockets will quickly get saturated, resulting in a useless server (unless it's used by one or two persons)
4. Telegram has this, plus obfuscation, plus VoIP, plus video calls, plus everything in between, sponsoring included. Telegram has had this for a very long time, without the resources of WhatsApp. I am really disappointed in you guys :D

**Comment by Terabyte1385** [comment]
If you don't like it, you don't need to use it

**Comment by abiusx** [comment]
If you don't like my feedback, you don't have to read it.

**Comment by Terabyte1385** [comment]
Firstly, how can I have an opinion about your "feedback" without first reading it?

Secondly, let me clarify. This issue is practically useless. It doesn't foster improvements to the software. It doesn't ask for suggestions. Constructive criticism is always welcome, but your "disappointment" in WhatsApp really has no place here unless you can make it better.

**Comment by abiusx** [comment]
> Firstly, how can I have an opinion about your "feedback" without first reading it?

Unread it after reading it.

> Secondly, let me clarify. This issue is practically useless. It doesn't foster improvements to the software. It doesn't ask for suggestions. Constructive criticism is always welcome, but your "disappointment" in WhatsApp really has no place here unless you can make it better.

Let me clarify the ticket. This tool is practically useless. The way it can become useful is for it to be rewritten, or at least admit that it's just a Dockerfile glorified as a tool, and should be gist instead. That's a suggestion!

Of course I can make it better. But why would I, when I see this is the standard?

**Comment by slawlor** [comment]
Just as a reference for others who come across this issue

1. They're is a pre built container available at 
```
docker pull facebook/whatsapp_proxy:latest
```

2. This repository contains the core docker file and settings to build that container, should anyone want to customize it themselves or run it say in a cluster. (Eg k8s)

3. The detection and blockage of these proxies is something we are constantly evaluating. Unfortunately what's up does not use HTTP(S) to connect to its core services, so standard proxying techniques built on HTTP protocols and standards don't work here. This is why the implementation here is simply a TCP proxy which forwards the bytes to our back end services. You're welcome to run any TCP proxy you wish, and if you can find a way to improve the detectability of it we would welcome any and all suggestions

**Comment by slawlor** [comment]
Additionally it does now support media however VoIP is still wip

**Comment by Terabyte1385** [comment]
> Of course I can make it better. But why would I, when I see this is the standard? 

@abiusx 

Go ahead. Make it better. Your contributions will be felt throughout, and many will choose your solution than this one.

___

@slawlor 

Thank you for further clarification!

**Comment by abiusx** [comment]
> > Of course I can make it better. But why would I, when I see this is the standard?
> 
> @abiusx
> 

Now  we are entering constructive criticism domain. Thank you for taking this road instead of feeling personally attacked.
I have already done so in several open-source projects. Naturally one wouldn't do such things under their identifiable username ;)

**Comment by Terabyte1385** [comment]
> > > Of course I can make it better. But why would I, when I see this is the standard?
> 
> > 
> 
> > @abiusx
> 
> > 
> 
> 
> 
> Now  we are entering constructive criticism domain. Thank you for taking this road instead of feeling personally attacked.
> 
> I have already done so in several open-source projects. Naturally one wouldn't do such things under their identifiable username ;)
> 
> 

Alright. Thank you for your understanding. I apologise if you felt attacked in any way. I appreciate your professionalism
