### ISSUE TITLE
Cannot bind socket

### ISSUE THREAD

**Issue by capsload2** [WhatsApp/proxy#99]
Just getting this error while reading the docker logs.

```
[ALERT] (23) : Binding [/usr/local/etc/haproxy/haproxy.cfg:60] for frontend haproxy_v4_http: cannot bind socket (Permission denied) for [0.0.0.0:80]
[ALERT] (23) : Binding [/usr/local/etc/haproxy/haproxy.cfg:69] for frontend haproxy_v4_https: cannot bind socket (Permission denied) for [0.0.0.0:443]
```

How can i fix that?

Ubuntu 22.04 x64 OpenVZ

**Comment by eozturk1** [comment]
There was a similar issue mentioned in https://github.com/docker-library/haproxy/issues/160. Could you try the solution proposed there?

**Comment by capsload2** [comment]
This worked! Thanks
